ALTER TABLE OA_SHIPMENT_ADDRESS_DTL RENAME TO OA_SERVICE_ADDRESS_DTL;
ALTER TABLE OA_SERVICE_ADDRESS_DTL RENAME COLUMN SHIPMENT_ADDRESS_ID TO SERVICE_ADDRESS_ID;
ALTER TABLE OA_SERVICE_ADDRESS_DTL RENAME CONSTRAINT SHIPMENT_ADDRESS_ID_PK TO SERVICE_ADDRESS_ID_PK;
ALTER TABLE OA_SERVICE_ADDRESS_DTL RENAME COLUMN SHIPMENT_ADDRESS_LINE_1 TO ADDRESS_LINE_1;
ALTER TABLE OA_SERVICE_ADDRESS_DTL RENAME COLUMN SHIPMENT_ADDRESS_LINE_2 TO ADDRESS_LINE_2;

ALTER INDEX SHIPMENT_ADDRESS_ID_PK RENAME TO SERVICE_ADDRESS_ID_PK;

ALTER TABLE ONEASSIST_SP.OA_SHIPMENT_DOC_DTL ADD SERVICE_REQUEST_ID NUMBER(10,0);

ALTER TABLE ONEASSIST_SP.OA_SHIPMENT_DOC_DTL RENAME TO ONEASSIST_SP.OA_SERVICE_DOC_DTL;
ALTER TABLE ONEASSIST_SP.OA_SHIPMENT_DOC_DTL RENAME COLUMN SHIPMENT_DOC_ID to DOC_ID;
RENAME ONEASSIST_SP.SEQ_OA_SHIPMENT_DOC_DTL to ONEASSIST_SP.SEQ_OA_SERVICE_DOC_DTL;

ALTER TABLE ONEASSIST_SP.OA_SERVICE_DOC_DTL RENAME CONSTRAINT ONEASSIST_SP.SHIPMENT_DOC_ID_PK TO ONEASSIST_SP.SERVICE_DOC_ID_PK;
ALTER INDEX ONEASSIST_SP.SHIPMENT_DOC_ID_PK RENAME TO ONEASSIST_SP.SERVICE_DOC_ID_PK;

rename SEQ_OA_SHIPMENT_ADDRESS_DTL to SEQ_OA_SERVICE_ADDRESS_DTL;
--------------Table renaming scripts ends

alter table ONEASSIST_SP.oa_service_request_dtl modify CREATED_BY VARCHAR2(100);
alter table ONEASSIST_SP.oa_service_request_dtl modify MODIFIED_BY VARCHAR2(100);

ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL ADD (ASSIGNEE NUMBER(10,0),
SERVICE_SCHEDULE_STARTTIME TIMESTAMP (6),
SERVICE_SCHEDULE_ENDTIME TIMESTAMP (6),
SERVICE_PARTNER_CODE NUMBER(10,0),
SERVICE_PARTNER_BU_CODE NUMBER(10,0),
WORKFLOW_PROCESS_ID VARCHAR2(64),
WORKFLOW_DATA CLOB,
PROD_CODE VARCHAR2(20),
INITIATING_SYSTEM NUMBER(2,0),
REFERENCE_NO VARCHAR2(10),
WORKFLOW_STAGE VARCHAR2(10),
WORKFLOW_ALERT VARCHAR2(10),
WORKFLOW_STAGE_STATUS VARCHAR2(10),IS_SELF_REPAIR VARCHAR2(2),
WORKFLOW_PROC_DEF_KEY VARCHAR2(255),SERVICE_DUEDATETIME TIMESTAMP(6));
ALTER TABLE ONEASSIST_SP.OA_PINCODE_SERV_FULFILMENT_MST ADD (PARTNER_BU_CODE VARCHAR2(10));
CREATE TABLE ONEASSIST_SP.OA_SERVICE_CONFIG
(
ID NUMBER(10,0) NOT NULL,
SERVICE_CODE VARCHAR2(50 BYTE) NOT NULL,
CONFIG_KEY VARCHAR2(500 BYTE) NOT NULL,
PARAM_NAME VARCHAR2(50 BYTE),
PARAM_VALUE VARCHAR2(1000 BYTE),
STATUS VARCHAR2(5 BYTE),
CREATED_BY VARCHAR2(200 BYTE) ,
CREATED_ON TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
MODIFIED_BY VARCHAR2(200 BYTE) ,
MODIFIED_ON TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
PARAM_TYPE VARCHAR2(500 BYTE)
);
CREATE UNIQUE INDEX ONEASSIST_SP.SERVICE_CONFIG_ID_PK ON ONEASSIST_SP.OA_SERVICE_CONFIG (ID) ;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_CONFIG ADD CONSTRAINT SERVICE_CONFIG_ID_PK PRIMARY KEY (ID) USING INDEX ENABLE;

CREATE SEQUENCE ONEASSIST_SP.SEQ_OA_SERVICE_CONFIG MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.OA_SERVICE_CONFIG TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.OA_SERVICE_CONFIG FOR ONEASSIST_SP.OA_SERVICE_CONFIG;

GRANT SELECT,ALTER ON ONEASSIST_SP.SEQ_OA_SERVICE_CONFIG TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.SEQ_OA_SERVICE_CONFIG FOR ONEASSIST_SP.SEQ_OA_SERVICE_CONFIG;

COMMENT ON TABLE ONEASSIST_SP.OA_SERVICE_CONFIG IS 'This is master information to store cofiguration data.';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.ID IS 'PK';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.SERVICE_CODE IS 'Service code refers to service and category eg.EW-HA';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.CONFIG_KEY IS 'This is refers to configuration to events,workflow such as EVENT,STATUS,WORKFLOW';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.PARAM_TYPE IS 'It is option field,similar to config key';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.PARAM_NAME IS 'It stores parameter name';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.PARAM_VALUE IS 'Stores value for the respective param name';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.STATUS IS 'Status of the corresponding Param';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.CREATED_ON IS 'record creation date';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.CREATED_BY IS 'record created by';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.MODIFIED_ON IS 'record modification date';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_CONFIG.MODIFIED_BY IS 'record modified by';
----------------------------------------------------------
CREATE TABLE ONEASSIST_SP.OA_SERVICE_TASK_MST (SERVICE_TASK_ID NUMBER(10,0),TASK_NAME VARCHAR2(100),TASK_DESCRIPTION VARCHAR2(500),
TASK_TYPE VARCHAR2(50),PROD_CODE VARCHAR2(50),COST NUMBER(14,2),IS_INSURANCE_COVERED VARCHAR2(1 BYTE),PRODUCT_VARIANT_ID NUMBER(10),STATUS VARCHAR2(2 BYTE),
CREATED_ON TIMESTAMP (6),CREATED_BY VARCHAR2(10), MODIFIED_ON TIMESTAMP (6), MODIFIED_BY VARCHAR2(10));
COMMENT ON TABLE ONEASSIST_SP.OA_SERVICE_TASK_MST IS 'This is master information to store diagnosis and spare parts information.';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.SERVICE_TASK_ID IS 'PK';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.TASK_NAME IS 'Stores the task name such as Screen broken, Replace TV Panel, Replace TV Stand, Pickup';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.TASK_DESCRIPTION IS 'Description about task';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.TASK_TYPE IS 'Type of the task i.e ,Diagnosis, Sparepart, Transportation';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.PROD_CODE IS 'Gives product code i.e, TV, Mobile, Laptop, Wallet';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.COST IS 'task cost';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.IS_INSURANCE_COVERED IS 'Whether insurance is covered for the task.,Y-insurance covred,N-Insuarnce is not covered';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.STATUS IS 'Status of the task.i.e,A-Active, X-Cancelled, P-Pending';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.CREATED_ON IS 'record creation date';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.CREATED_BY IS 'record created by';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.MODIFIED_ON IS 'record modification date';
COMMENT ON COLUMN ONEASSIST_SP.OA_SERVICE_TASK_MST.MODIFIED_BY IS 'record modified by';
CREATE UNIQUE INDEX ONEASSIST_SP.SERVICE_TASK_ID_PK ON ONEASSIST_SP.OA_SERVICE_TASK_MST (SERVICE_TASK_ID) ;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_TASK_MST ADD CONSTRAINT SERVICE_TASK_ID_PK PRIMARY KEY (SERVICE_TASK_ID) USING INDEX ENABLE;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_TASK_MST MODIFY (SERVICE_TASK_ID NOT NULL ENABLE);

CREATE SEQUENCE ONEASSIST_SP.SEQ_OA_SERVICE_TASK_MST MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.OA_SERVICE_TASK_MST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.OA_SERVICE_TASK_MST FOR ONEASSIST_SP.OA_SERVICE_TASK_MST;

GRANT SELECT,ALTER ON ONEASSIST_SP.SEQ_OA_SERVICE_TASK_MST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.SEQ_OA_SERVICE_TASK_MST FOR ONEASSIST_SP.SEQ_OA_SERVICE_TASK_MST;
---------------------------------------------------------------------
------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW ONEASSIST_SP.SHIPMENT_SEARCH_RESULT_VIEW AS SELECT rownum AS ID,
shipment.shipment_id AS shipmentId,
serviceType.SERVICE_REQUEST_TYPE_ID AS serviceRequestTypeId,
service.REF_PRIMARY_TRACKING_NO AS primaryTrackingNumber,
shipment.CURRENT_STAGE AS currentStage,
shipment.logistic_partner_code AS logisticPartnerCode,
shipment.logistic_partner_ref_track_no AS logisticPartnerRefTrackingNo,
shipment.created_on AS createdOn,
shipment.modified_on AS modifiedOn,
shipment.hub_id AS hubId,
shipment.status AS shipmentStatus,
servicetype.service_request_type AS serviceName,
originAddress.PINCODE AS originPincode,
destinationAddress.pincode AS destinationPincode,
pod.podDocTypeId AS podDocTypeId,
label.labelDocTypeId AS labelDocTypeId,
label.labelDocName AS lablDocTypeName,
pod.podDocName AS podDocTypeName,
pod.podMongoRefId AS podMongoRefId,
pod.podFileName AS podDocumentName,
label.labelMongoRefId AS labelMongoRefId,
label.labelFileName AS labelDocumentName,
shipment.BOX_ACTUAL_LENGTH AS boxActualLength,
shipment.BOX_ACTUAL_WIDTH AS boxActualWidth,
shipment.BOX_ACTUAL_HEIGHT AS boxActualHeight,
shipment.BOX_ACTUAL_WEIGHT AS boxActualWeight,
shipment.SHIPMENT_DECLARE_VALUE AS shipmentDeclareValue,
asset.ASSET_PIECE_COUNT AS assetPieceCount,
asset.ASSET_CATEGORY_NAME AS assetCategoryName,
originAddress.SERVICE_ADDRESS_ID AS originalAddressId,
originAddress.ADDRESS_LINE_1 AS originAddressLine1,
originAddress.ADDRESS_LINE_2 AS originAddressLine2,
originAddress.LANDMARK AS originLandmark,
originAddress.DISTRICT AS originDistrict,
originAddress.MOBILE_NO AS originMobileNO,
originAddress.COUNTRY_CODE AS originCountryCode,
originAddress.EMAIL AS originAddressEmail,
originAddress.ADDRESSEE_FULL_NAME AS originAddresseeFullName,
destinationAddress.SERVICE_ADDRESS_ID AS destinationAddressId,
destinationAddress.ADDRESS_LINE_1 AS destinationAddressLine1,
destinationAddress.ADDRESS_LINE_2 AS destinationAddressLine2,
destinationAddress.LANDMARK AS destinationLandmark,
destinationAddress.DISTRICT AS destinationDistrict,
destinationAddress.MOBILE_NO AS destinationMobileNO,
destinationAddress.COUNTRY_CODE AS destinationCountryCode,
destinationAddress.EMAIL AS destinationAddressEmail,
destinationAddress.ADDRESSEE_FULL_NAME AS destinationAddresseeFullName,
shipment.BOX_COUNT AS shipmentBoxCount,
shipment.SHIPMENT_TYPE AS shipmentType,
shipment.service_request_id AS SERVICE_REQUEST_ID,
shipment.FAILURE_REASON AS reasonForFailure,
asset.ASSET_MODEL_NAME AS ASSET_MODEL_NAME,
asset.ASSET_MAKE_NAME AS ASSET_MAKE_NAME,
label.labelDocId AS labelDocId,
pod.podDocId AS podDocId
FROM ONEASSIST_SP.OA_SHIPMENT_DTL shipment
INNER JOIN ONEASSIST_SP.OA_SERVICE_ADDRESS_DTL originAddress
ON shipment.origin_addrees_id = originAddress.service_address_id
INNER JOIN ONEASSIST_SP.OA_SERVICE_ADDRESS_DTL destinationAddress
ON shipment.DESTINATION_ADDREES_ID = destinationAddress.service_address_id
LEFT JOIN ONEASSIST_SP.OA_SHIPMENT_ASSET_DTL asset
ON shipment.shipment_id = asset.shipment_id
INNER JOIN ONEASSIST_SP.OA_SERVICE_REQUEST_DTL service
ON shipment.SERVICE_REQUEST_ID = service.SERVICE_REQUEST_ID
INNER JOIN ONEASSIST_SP.OA_SERVICE_REQUEST_TYPE_MST serviceType
ON service.SERVICE_REQUEST_TYPE_ID = serviceType.SERVICE_REQUEST_TYPE_ID
LEFT JOIN
(SELECT dtl.doc_type_id AS podDocTypeId,
typemst.doc_name AS podDocName,
dtl.file_name AS podFileName,
dtl.service_request_id AS podShipmentId,
dtl.STORAGE_REF_ID AS podMongoRefId,
dtl.DOC_ID as podDocId
FROM OA_SERVICE_DOC_DTL dtl
INNER JOIN oa_doc_type_mst typemst
ON dtl.doc_type_id = typemst.doc_type_id
AND typemst.doc_name ='SHIPMENT_PROOF_OF_DELIVERY'
AND dtl.status ='A'
)pod ON shipment.service_request_id = pod.podShipmentId and pod.podFileName LIKE CONCAT(CONCAT('%',shipment.logistic_partner_ref_track_no), '%')
LEFT OUTER JOIN
(SELECT dtl.doc_type_id AS labelDocTypeId,
typemst.doc_name AS labelDocName,
dtl.file_name AS labelFileName,
dtl.service_request_id AS labelShipmentId,
dtl.STORAGE_REF_ID AS labelMongoRefId,
dtl.DOC_ID as labelDocId
FROM OA_SERVICE_DOC_DTL dtl
INNER JOIN oa_doc_type_mst typemst
ON dtl.doc_type_id = typemst.doc_type_id
AND typemst.doc_name ='SHIPMENT_LABEL'
AND dtl.status ='A'
)label ON shipment.service_request_id = label.labelShipmentId and label.labelFileName LIKE CONCAT(CONCAT('%',shipment.logistic_partner_ref_track_no), '%')
ORDER BY shipment.shipment_id DESC;
--------------------------------
CREATE OR REPLACE FORCE VIEW ONEASSIST_SP.SVC_REQ_SHIPMENT_DETAILS_VIEW AS
SELECT rownum AS ID,
shipment.shipment_id AS shipmentId,
shipment.SHIPMENT_TYPE AS shipmentType,
shipment.CURRENT_STAGE AS currentStage,
shipment.logistic_partner_code AS logisticPartnerCode,
shipment.logistic_partner_ref_track_no AS logisticPartnerRefTrackingNo,
shipment.created_on AS shipmentCreatedOn,
shipment.modified_on AS shipmentModifiedOn,
shipment.hub_id AS hubId,
shipment.status AS shipmentStatus,
shipment.RECIPIENT AS shipRecipient,
shipment.SENDER AS shipSender,
shipment.SENT_BY AS shipSentBy,
shipment.RECEIVED_BY AS shipReceivedBy,
shipment.SCHEDULED_PICKUP_DATE AS shipSchdPickupDate,
shipment.BOX_COUNT AS shipmentBoxCount,
shipment.BOX_ACTUAL_LENGTH AS boxActualLength,
shipment.BOX_ACTUAL_WIDTH AS boxActualWidth,
shipment.BOX_ACTUAL_HEIGHT AS boxActualHeight,
shipment.BOX_ACTUAL_WEIGHT AS boxActualWeight,
shipment.BOX_LENGTH_UNIT AS boxLengthUnit,
shipment.BOX_WIDTH_UNIT AS boxWidthUnit,
shipment.BOX_HEIGHT_UNIT AS boxHeightUnit,
shipment.BOX_WEIGHT_UNIT AS boxWeightUnit,
shipment.SHIPMENT_DECLARE_VALUE AS shipmentDeclareValue,
service.SERVICE_REQUEST_ID AS serviceRequestId,
service.REF_PRIMARY_TRACKING_NO AS primaryTrackingNumber,
service.REF_SECONDARY_TRACKING_NO AS refSvcSecTrackingNum,
service.REQUEST_DESCRIPTION AS serviceReqDesc,
service.REQUEST_RAISED_BY AS serviceReqRaisedBy,
service.REQUEST_RAISED_FROM AS serviceReqRaisedFrom,
service.STATUS AS serviceReqStatus,
service.CREATED_ON AS serviceReqCreatedOn,
service.MODIFIED_ON AS serviceReqModifiedOn,
serviceType.SERVICE_REQUEST_TYPE_ID AS serviceRequestTypeId,
servicetype.service_request_type AS serviceName,
originAddress.PINCODE AS originPincode,
originAddress.SERVICE_ADDRESS_ID AS originalAddressId,
originAddress.ADDRESS_LINE_1 AS originShipmentAddrLine1,
originAddress.ADDRESS_LINE_2 AS originShipmentAddrLine2,
originAddress.LANDMARK AS originLandmark,
originAddress.DISTRICT AS originDistrict,
originAddress.MOBILE_NO AS originMobileNO,
originAddress.COUNTRY_CODE AS originCountryCode,
originAddress.EMAIL AS originAddressEmail,
originAddress.ADDRESSEE_FULL_NAME AS originAddresseeFullName,
destinationAddress.pincode AS destinationPincode,
destinationAddress.SERVICE_ADDRESS_ID AS destinationAddressId,
destinationAddress.ADDRESS_LINE_1 AS destinationAddrLine1,
destinationAddress.ADDRESS_LINE_2 AS destinationAddrLine2,
destinationAddress.LANDMARK AS destinationLandmark,
destinationAddress.DISTRICT AS destinationDistrict,
destinationAddress.MOBILE_NO AS destinationMobileNO,
destinationAddress.COUNTRY_CODE AS destinationCountryCode,
destinationAddress.EMAIL AS destinationAddressEmail,
destinationAddress.ADDRESSEE_FULL_NAME AS destinationAddresseeFullName,
asset.SHIPMENT_ASSET_ID AS shipmentAssetId,
asset.ASSET_PIECE_COUNT AS assetPieceCount,
asset.ASSET_CATEGORY_NAME AS assetCategoryName,
asset.ASSET_MAKE_NAME AS assetMakeName,
asset.ASSET_MODEL_NAME AS assetModelName,
asset.ASSET_DECLARE_VALUE AS assetDeclareValue,
asset.ASSET_ACTUAL_LENGTH AS assetActualLength,
asset.ASSET_ACTUAL_WIDTH AS assetActualWidth,
asset.ASSET_ACTUAL_HEIGHT AS assetActualHeight,
asset.ASSET_ACTUAL_WEIGHT AS assetActualWeight,
asset.REMARKS AS assetRemarks,
asset.ASSET_LENGTH_UNIT AS assetLengthUnit,
asset.ASSET_WIDTH_UNIT AS assetWidthUnit,
asset.ASSET_HEIGHT_UNIT AS assetHeightUnit,
asset.ASSET_WEIGHT_UNIT AS assetWeightUnit,
asset.ASSET_REFERENCE_NO AS assetReferenceNo
FROM ONEASSIST_SP.OA_SHIPMENT_DTL shipment
LEFT JOIN ONEASSIST_SP.OA_SERVICE_ADDRESS_DTL originAddress
ON shipment.origin_addrees_id = originAddress.service_address_id
LEFT JOIN ONEASSIST_SP.OA_SERVICE_ADDRESS_DTL destinationAddress
ON shipment.DESTINATION_ADDREES_ID = destinationAddress.service_address_id
LEFT JOIN ONEASSIST_SP.OA_SHIPMENT_ASSET_DTL asset
ON shipment.shipment_id = asset.shipment_id
RIGHT JOIN ONEASSIST_SP.OA_SERVICE_REQUEST_DTL service
ON shipment.SERVICE_REQUEST_ID = service.SERVICE_REQUEST_ID
INNER JOIN ONEASSIST_SP.OA_SERVICE_REQUEST_TYPE_MST serviceType
ON service.SERVICE_REQUEST_TYPE_ID = serviceType.SERVICE_REQUEST_TYPE_ID
WHERE (shipment.STATUS IS NULL
OR shipment.STATUS <>'R')
ORDER BY shipment.shipment_id DESC;


--------------------------------------------------------
-- DDL for Table ACT_EVT_LOG
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_EVT_LOG" 
( "LOG_NR_" NUMBER(19,0), 
"TYPE_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"EXECUTION_ID_" NVARCHAR2(64), 
"TASK_ID_" NVARCHAR2(64), 
"TIME_STAMP_" TIMESTAMP (6), 
"USER_ID_" NVARCHAR2(255), 
"DATA_" BLOB, 
"LOCK_OWNER_" NVARCHAR2(255), 
"LOCK_TIME_" TIMESTAMP (6), 
"IS_PROCESSED_" NUMBER(3,0) DEFAULT 0
);

--------------------------------------------------------
-- DDL for Table ACT_GE_BYTEARRAY
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_GE_BYTEARRAY" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"NAME_" NVARCHAR2(255), 
"DEPLOYMENT_ID_" NVARCHAR2(64), 
"BYTES_" BLOB, 
"GENERATED_" NUMBER(1,0)
);
--------------------------------------------------------
-- DDL for Table ACT_GE_PROPERTY
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_GE_PROPERTY" 
( "NAME_" NVARCHAR2(64), 
"VALUE_" NVARCHAR2(300), 
"REV_" NUMBER(*,0)
);
--------------------------------------------------------
-- DDL for Table ACT_HI_ACTINST
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" 
( "ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"EXECUTION_ID_" NVARCHAR2(64), 
"ACT_ID_" NVARCHAR2(255), 
"TASK_ID_" NVARCHAR2(64), 
"CALL_PROC_INST_ID_" NVARCHAR2(64), 
"ACT_NAME_" NVARCHAR2(255), 
"ACT_TYPE_" NVARCHAR2(255), 
"ASSIGNEE_" NVARCHAR2(255), 
"START_TIME_" TIMESTAMP (6), 
"END_TIME_" TIMESTAMP (6), 
"DURATION_" NUMBER(19,0), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
);
--------------------------------------------------------
-- DDL for Table ACT_HI_ATTACHMENT
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_ATTACHMENT" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"USER_ID_" NVARCHAR2(255), 
"NAME_" NVARCHAR2(255), 
"DESCRIPTION_" NVARCHAR2(2000), 
"TYPE_" NVARCHAR2(255), 
"TASK_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"URL_" NVARCHAR2(2000), 
"CONTENT_ID_" NVARCHAR2(64), 
"TIME_" TIMESTAMP (6)
);
--------------------------------------------------------
-- DDL for Table ACT_HI_COMMENT
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_COMMENT" 
( "ID_" NVARCHAR2(64), 
"TYPE_" NVARCHAR2(255), 
"TIME_" TIMESTAMP (6), 
"USER_ID_" NVARCHAR2(255), 
"TASK_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"ACTION_" NVARCHAR2(255), 
"MESSAGE_" NVARCHAR2(2000), 
"FULL_MSG_" BLOB
) ;
--------------------------------------------------------
-- DDL for Table ACT_HI_DETAIL
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" 
( "ID_" NVARCHAR2(64), 
"TYPE_" NVARCHAR2(255), 
"PROC_INST_ID_" NVARCHAR2(64), 
"EXECUTION_ID_" NVARCHAR2(64), 
"TASK_ID_" NVARCHAR2(64), 
"ACT_INST_ID_" NVARCHAR2(64), 
"NAME_" NVARCHAR2(255), 
"VAR_TYPE_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"TIME_" TIMESTAMP (6), 
"BYTEARRAY_ID_" NVARCHAR2(64), 
"DOUBLE_" NUMBER(*,10), 
"LONG_" NUMBER(19,0), 
"TEXT_" NVARCHAR2(2000), 
"TEXT2_" NVARCHAR2(2000)
);
--------------------------------------------------------
-- DDL for Table ACT_HI_IDENTITYLINK
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_IDENTITYLINK" 
( "ID_" NVARCHAR2(64), 
"GROUP_ID_" NVARCHAR2(255), 
"TYPE_" NVARCHAR2(255), 
"USER_ID_" NVARCHAR2(255), 
"TASK_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64)
);
--------------------------------------------------------
-- DDL for Table ACT_HI_PROCINST
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" 
( "ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"BUSINESS_KEY_" NVARCHAR2(255), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"START_TIME_" TIMESTAMP (6), 
"END_TIME_" TIMESTAMP (6), 
"DURATION_" NUMBER(19,0), 
"START_USER_ID_" NVARCHAR2(255), 
"START_ACT_ID_" NVARCHAR2(255), 
"END_ACT_ID_" NVARCHAR2(255), 
"SUPER_PROCESS_INSTANCE_ID_" NVARCHAR2(64), 
"DELETE_REASON_" NVARCHAR2(2000), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
"NAME_" NVARCHAR2(255)
);
--------------------------------------------------------
-- DDL for Table ACT_HI_TASKINST
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_TASKINST" 
( "ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"TASK_DEF_KEY_" NVARCHAR2(255), 
"PROC_INST_ID_" NVARCHAR2(64), 
"EXECUTION_ID_" NVARCHAR2(64), 
"PARENT_TASK_ID_" NVARCHAR2(64), 
"NAME_" NVARCHAR2(255), 
"DESCRIPTION_" NVARCHAR2(2000), 
"OWNER_" NVARCHAR2(255), 
"ASSIGNEE_" NVARCHAR2(255), 
"START_TIME_" TIMESTAMP (6), 
"CLAIM_TIME_" TIMESTAMP (6), 
"END_TIME_" TIMESTAMP (6), 
"DURATION_" NUMBER(19,0), 
"DELETE_REASON_" NVARCHAR2(2000), 
"PRIORITY_" NUMBER(*,0), 
"DUE_DATE_" TIMESTAMP (6), 
"FORM_KEY_" NVARCHAR2(255), 
"CATEGORY_" NVARCHAR2(255), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
);
--------------------------------------------------------
-- DDL for Table ACT_HI_VARINST
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_HI_VARINST" 
( "ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"EXECUTION_ID_" NVARCHAR2(64), 
"TASK_ID_" NVARCHAR2(64), 
"NAME_" NVARCHAR2(255), 
"VAR_TYPE_" NVARCHAR2(100), 
"REV_" NUMBER(*,0), 
"BYTEARRAY_ID_" NVARCHAR2(64), 
"DOUBLE_" NUMBER(*,10), 
"LONG_" NUMBER(19,0), 
"TEXT_" NVARCHAR2(2000), 
"TEXT2_" NVARCHAR2(2000), 
"CREATE_TIME_" TIMESTAMP (6), 
"LAST_UPDATED_TIME_" TIMESTAMP (6)
) ;
--------------------------------------------------------
-- DDL for Table ACT_ID_GROUP
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_ID_GROUP" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"NAME_" NVARCHAR2(255), 
"TYPE_" NVARCHAR2(255)
);
--------------------------------------------------------
-- DDL for Table ACT_ID_INFO
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_ID_INFO" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"USER_ID_" NVARCHAR2(64), 
"TYPE_" NVARCHAR2(64), 
"KEY_" NVARCHAR2(255), 
"VALUE_" NVARCHAR2(255), 
"PASSWORD_" BLOB, 
"PARENT_ID_" NVARCHAR2(255)
);
--------------------------------------------------------
-- DDL for Table ACT_ID_MEMBERSHIP
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" 
( "USER_ID_" NVARCHAR2(64), 
"GROUP_ID_" NVARCHAR2(64)
);
--------------------------------------------------------
-- DDL for Table ACT_ID_USER
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_ID_USER" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"FIRST_" NVARCHAR2(255), 
"LAST_" NVARCHAR2(255), 
"EMAIL_" NVARCHAR2(255), 
"PWD_" NVARCHAR2(255), 
"PICTURE_ID_" NVARCHAR2(64)
);
--------------------------------------------------------
-- DDL for Table ACT_RE_DEPLOYMENT
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RE_DEPLOYMENT" 
( "ID_" NVARCHAR2(64), 
"NAME_" NVARCHAR2(255), 
"CATEGORY_" NVARCHAR2(255), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
"DEPLOY_TIME_" TIMESTAMP (6)
);
--------------------------------------------------------
-- DDL for Table ACT_RE_MODEL
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RE_MODEL" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"NAME_" NVARCHAR2(255), 
"KEY_" NVARCHAR2(255), 
"CATEGORY_" NVARCHAR2(255), 
"CREATE_TIME_" TIMESTAMP (6), 
"LAST_UPDATE_TIME_" TIMESTAMP (6), 
"VERSION_" NUMBER(*,0), 
"META_INFO_" NVARCHAR2(2000), 
"DEPLOYMENT_ID_" NVARCHAR2(64), 
"EDITOR_SOURCE_VALUE_ID_" NVARCHAR2(64), 
"EDITOR_SOURCE_EXTRA_VALUE_ID_" NVARCHAR2(64), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
);
--------------------------------------------------------
-- DDL for Table ACT_RE_PROCDEF
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"CATEGORY_" NVARCHAR2(255), 
"NAME_" NVARCHAR2(255), 
"KEY_" NVARCHAR2(255), 
"VERSION_" NUMBER(*,0), 
"DEPLOYMENT_ID_" NVARCHAR2(64), 
"RESOURCE_NAME_" NVARCHAR2(2000), 
"DGRM_RESOURCE_NAME_" VARCHAR2(4000 BYTE), 
"DESCRIPTION_" NVARCHAR2(2000), 
"HAS_START_FORM_KEY_" NUMBER(1,0), 
"HAS_GRAPHICAL_NOTATION_" NUMBER(1,0), 
"SUSPENSION_STATE_" NUMBER(*,0), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
) ;
--------------------------------------------------------
-- DDL for Table ACT_RU_EVENT_SUBSCR
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"EVENT_TYPE_" NVARCHAR2(255), 
"EVENT_NAME_" NVARCHAR2(255), 
"EXECUTION_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"ACTIVITY_ID_" NVARCHAR2(64), 
"CONFIGURATION_" NVARCHAR2(255), 
"CREATED_" TIMESTAMP (6), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
) ;
--------------------------------------------------------
-- DDL for Table ACT_RU_EXECUTION
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"PROC_INST_ID_" NVARCHAR2(64), 
"BUSINESS_KEY_" NVARCHAR2(255), 
"PARENT_ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"SUPER_EXEC_" NVARCHAR2(64), 
"ACT_ID_" NVARCHAR2(255), 
"IS_ACTIVE_" NUMBER(1,0), 
"IS_CONCURRENT_" NUMBER(1,0), 
"IS_SCOPE_" NUMBER(1,0), 
"IS_EVENT_SCOPE_" NUMBER(1,0), 
"SUSPENSION_STATE_" NUMBER(*,0), 
"CACHED_ENT_STATE_" NUMBER(*,0), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
"NAME_" NVARCHAR2(255), 
"LOCK_TIME_" TIMESTAMP (6)
);
--------------------------------------------------------
-- DDL for Table ACT_RU_IDENTITYLINK
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"GROUP_ID_" NVARCHAR2(255), 
"TYPE_" NVARCHAR2(255), 
"USER_ID_" NVARCHAR2(255), 
"TASK_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64)
) ;
--------------------------------------------------------
-- DDL for Table ACT_RU_JOB
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_JOB" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"TYPE_" NVARCHAR2(255), 
"LOCK_EXP_TIME_" TIMESTAMP (6), 
"LOCK_OWNER_" NVARCHAR2(255), 
"EXCLUSIVE_" NUMBER(1,0), 
"EXECUTION_ID_" NVARCHAR2(64), 
"PROCESS_INSTANCE_ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"RETRIES_" NUMBER(*,0), 
"EXCEPTION_STACK_ID_" NVARCHAR2(64), 
"EXCEPTION_MSG_" NVARCHAR2(2000), 
"DUEDATE_" TIMESTAMP (6), 
"REPEAT_" NVARCHAR2(255), 
"HANDLER_TYPE_" NVARCHAR2(255), 
"HANDLER_CFG_" NVARCHAR2(2000), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT ''
) ;
--------------------------------------------------------
-- DDL for Table ACT_RU_TASK
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_TASK" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"EXECUTION_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"PROC_DEF_ID_" NVARCHAR2(64), 
"NAME_" NVARCHAR2(255), 
"PARENT_TASK_ID_" NVARCHAR2(64), 
"DESCRIPTION_" NVARCHAR2(2000), 
"TASK_DEF_KEY_" NVARCHAR2(255), 
"OWNER_" NVARCHAR2(255), 
"ASSIGNEE_" NVARCHAR2(255), 
"DELEGATION_" NVARCHAR2(64), 
"PRIORITY_" NUMBER(*,0), 
"CREATE_TIME_" TIMESTAMP (6), 
"DUE_DATE_" TIMESTAMP (6), 
"CATEGORY_" NVARCHAR2(255), 
"SUSPENSION_STATE_" NUMBER(*,0), 
"TENANT_ID_" NVARCHAR2(255) DEFAULT '', 
"FORM_KEY_" NVARCHAR2(255)
) ;
--------------------------------------------------------
-- DDL for Table ACT_RU_VARIABLE
--------------------------------------------------------
CREATE TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" 
( "ID_" NVARCHAR2(64), 
"REV_" NUMBER(*,0), 
"TYPE_" NVARCHAR2(255), 
"NAME_" NVARCHAR2(255), 
"EXECUTION_ID_" NVARCHAR2(64), 
"PROC_INST_ID_" NVARCHAR2(64), 
"TASK_ID_" NVARCHAR2(64), 
"BYTEARRAY_ID_" NVARCHAR2(64), 
"DOUBLE_" NUMBER(*,10), 
"LONG_" NUMBER(19,0), 
"TEXT_" NVARCHAR2(2000), 
"TEXT2_" NVARCHAR2(2000)
);
SET DEFINE OFF;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_BYTEAR_DEPL" ON "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ("DEPLOYMENT_ID_");

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_ACT_INST_START" ON "ONEASSIST_SP"."ACT_HI_ACTINST" ("START_TIME_");

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_ACT_INST_END" ON "ONEASSIST_SP"."ACT_HI_ACTINST" ("END_TIME_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_ACT_INST_PROCINST" ON "ONEASSIST_SP"."ACT_HI_ACTINST" ("PROC_INST_ID_", "ACT_ID_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_ACT_INST_EXEC" ON "ONEASSIST_SP"."ACT_HI_ACTINST" ("EXECUTION_ID_", "ACT_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_DETAIL_TIME" ON "ONEASSIST_SP"."ACT_HI_DETAIL" ("TIME_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_DETAIL_NAME" ON "ONEASSIST_SP"."ACT_HI_DETAIL" ("NAME_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_DETAIL_TASK_ID" ON "ONEASSIST_SP"."ACT_HI_DETAIL" ("TASK_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_DETAIL_PROC_INST" ON "ONEASSIST_SP"."ACT_HI_DETAIL" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_DETAIL_ACT_INST" ON "ONEASSIST_SP"."ACT_HI_DETAIL" ("ACT_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_IDENT_LNK_USER" ON "ONEASSIST_SP"."ACT_HI_IDENTITYLINK" ("USER_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_IDENT_LNK_TASK" ON "ONEASSIST_SP"."ACT_HI_IDENTITYLINK" ("TASK_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_IDENT_LNK_PROCINST" ON "ONEASSIST_SP"."ACT_HI_IDENTITYLINK" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_PRO_INST_END" ON "ONEASSIST_SP"."ACT_HI_PROCINST" ("END_TIME_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_PRO_I_BUSKEY" ON "ONEASSIST_SP"."ACT_HI_PROCINST" ("BUSINESS_KEY_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_TASK_INST_PROCINST" ON "ONEASSIST_SP"."ACT_HI_TASKINST" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_PROCVAR_PROC_INST" ON "ONEASSIST_SP"."ACT_HI_VARINST" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_PROCVAR_NAME_TYPE" ON "ONEASSIST_SP"."ACT_HI_VARINST" ("NAME_", "VAR_TYPE_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_HI_PROCVAR_TASK_ID" ON "ONEASSIST_SP"."ACT_HI_VARINST" ("TASK_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_MEMB_GROUP" ON "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" ("GROUP_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_MEMB_USER" ON "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" ("USER_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_MODEL_SOURCE" ON "ONEASSIST_SP"."ACT_RE_MODEL" ("EDITOR_SOURCE_VALUE_ID_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_MODEL_SOURCE_EXTRA" ON "ONEASSIST_SP"."ACT_RE_MODEL" ("EDITOR_SOURCE_EXTRA_VALUE_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_MODEL_DEPLOYMENT" ON "ONEASSIST_SP"."ACT_RE_MODEL" ("DEPLOYMENT_ID_") ;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" ADD PRIMARY KEY ("ID_") USING INDEX ENABLE;

CREATE UNIQUE INDEX "ONEASSIST_SP"."ACT_UNIQ_PROCDEF" ON "ONEASSIST_SP"."ACT_RE_PROCDEF" ("KEY_", "VERSION_", "TENANT_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EVENT_SUBSCR" ON "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" ("EXECUTION_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EVENT_SUBSCR_CONFIG_" ON "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" ("CONFIGURATION_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EXEC_BUSKEY" ON "ONEASSIST_SP"."ACT_RU_EXECUTION" ("BUSINESS_KEY_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EXE_PROCINST" ON "ONEASSIST_SP"."ACT_RU_EXECUTION" ("PROC_INST_ID_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EXE_PARENT" ON "ONEASSIST_SP"."ACT_RU_EXECUTION" ("PARENT_ID_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EXE_SUPER" ON "ONEASSIST_SP"."ACT_RU_EXECUTION" ("SUPER_EXEC_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_EXE_PROCDEF" ON "ONEASSIST_SP"."ACT_RU_EXECUTION" ("PROC_DEF_ID_");

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_ATHRZ_PROCEDEF" ON "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ("PROC_DEF_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_IDL_PROCINST" ON "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_TSKASS_TASK" ON "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ("TASK_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_IDENT_LNK_USER" ON "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ("USER_ID_") ;
CREATE INDEX "ONEASSIST_SP"."ACT_IDX_IDENT_LNK_GROUP" ON "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ("GROUP_ID_");

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_JOB_EXCEPTION" ON "ONEASSIST_SP"."ACT_RU_JOB" ("EXCEPTION_STACK_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_TASK_EXEC" ON "ONEASSIST_SP"."ACT_RU_TASK" ("EXECUTION_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_TASK_PROCINST" ON "ONEASSIST_SP"."ACT_RU_TASK" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_TASK_PROCDEF" ON "ONEASSIST_SP"."ACT_RU_TASK" ("PROC_DEF_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_TASK_CREATE" ON "ONEASSIST_SP"."ACT_RU_TASK" ("CREATE_TIME_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_VAR_EXE" ON "ONEASSIST_SP"."ACT_RU_VARIABLE" ("EXECUTION_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_VAR_PROCINST" ON "ONEASSIST_SP"."ACT_RU_VARIABLE" ("PROC_INST_ID_") ;

CREATE INDEX "ONEASSIST_SP"."ACT_IDX_VAR_BYTEARRAY" ON "ONEASSIST_SP"."ACT_RU_VARIABLE" ("BYTEARRAY_ID_") ;

ALTER TABLE "ONEASSIST_SP"."ACT_EVT_LOG" ADD PRIMARY KEY ("LOG_NR_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_EVT_LOG" MODIFY ("TIME_STAMP_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ADD CHECK (GENERATED_ IN (1,0)) ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_GE_PROPERTY" ADD PRIMARY KEY ("NAME_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("ACT_TYPE_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("ACT_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("EXECUTION_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("PROC_INST_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("PROC_DEF_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ACTINST" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_HI_ATTACHMENT" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_ATTACHMENT" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_HI_COMMENT" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_COMMENT" MODIFY ("TIME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_COMMENT" MODIFY ("ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" MODIFY ("TIME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" MODIFY ("NAME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" MODIFY ("TYPE_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_DETAIL" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_HI_IDENTITYLINK" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" ADD UNIQUE ("PROC_INST_ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" MODIFY ("PROC_DEF_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" MODIFY ("PROC_INST_ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_PROCINST" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_HI_TASKINST" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_TASKINST" MODIFY ("START_TIME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_TASKINST" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_HI_VARINST" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_HI_VARINST" MODIFY ("NAME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_HI_VARINST" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_ID_GROUP" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_ID_INFO" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" ADD PRIMARY KEY ("USER_ID_", "GROUP_ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_ID_USER" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RE_DEPLOYMENT" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RE_MODEL" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_MODEL" MODIFY ("ID_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" ADD CONSTRAINT "ACT_UNIQ_PROCDEF" UNIQUE ("KEY_", "VERSION_", "TENANT_ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" ADD CHECK (HAS_GRAPHICAL_NOTATION_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" ADD CHECK (HAS_START_FORM_KEY_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" MODIFY ("VERSION_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" MODIFY ("KEY_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RE_PROCDEF" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" MODIFY ("CREATED_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" MODIFY ("EVENT_TYPE_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CHECK (IS_EVENT_SCOPE_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CHECK (IS_SCOPE_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CHECK (IS_CONCURRENT_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CHECK (IS_ACTIVE_ IN (1,0)) ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RU_JOB" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_JOB" ADD CHECK (EXCLUSIVE_ IN (1,0)) ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_JOB" MODIFY ("TYPE_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RU_JOB" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_RU_TASK" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" ADD PRIMARY KEY ("ID_")
USING INDEX ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" MODIFY ("NAME_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" MODIFY ("TYPE_" NOT NULL ENABLE);
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" MODIFY ("ID_" NOT NULL ENABLE);

ALTER TABLE "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ADD CONSTRAINT "ACT_FK_BYTEARR_DEPL" FOREIGN KEY ("DEPLOYMENT_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RE_DEPLOYMENT" ("ID_") ENABLE;


ALTER TABLE "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" ADD CONSTRAINT "ACT_FK_MEMB_GROUP" FOREIGN KEY ("GROUP_ID_")
REFERENCES "ONEASSIST_SP"."ACT_ID_GROUP" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_ID_MEMBERSHIP" ADD CONSTRAINT "ACT_FK_MEMB_USER" FOREIGN KEY ("USER_ID_")
REFERENCES "ONEASSIST_SP"."ACT_ID_USER" ("ID_") ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_DEPLOYMENT" FOREIGN KEY ("DEPLOYMENT_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RE_DEPLOYMENT" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE" FOREIGN KEY ("EDITOR_SOURCE_VALUE_ID_")
REFERENCES "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RE_MODEL" ADD CONSTRAINT "ACT_FK_MODEL_SOURCE_EXTRA" FOREIGN KEY ("EDITOR_SOURCE_EXTRA_VALUE_ID_")
REFERENCES "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EVENT_SUBSCR" ADD CONSTRAINT "ACT_FK_EVENT_EXEC" FOREIGN KEY ("EXECUTION_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PARENT" FOREIGN KEY ("PARENT_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PROCDEF" FOREIGN KEY ("PROC_DEF_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RE_PROCDEF" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_EXECUTION" ADD CONSTRAINT "ACT_FK_EXE_SUPER" FOREIGN KEY ("SUPER_EXEC_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_ATHRZ_PROCEDEF" FOREIGN KEY ("PROC_DEF_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RE_PROCDEF" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_IDL_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_IDENTITYLINK" ADD CONSTRAINT "ACT_FK_TSKASS_TASK" FOREIGN KEY ("TASK_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_TASK" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_JOB" ADD CONSTRAINT "ACT_FK_JOB_EXCEPTION" FOREIGN KEY ("EXCEPTION_STACK_ID_")
REFERENCES "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_EXE" FOREIGN KEY ("EXECUTION_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_PROCDEF" FOREIGN KEY ("PROC_DEF_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RE_PROCDEF" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_TASK" ADD CONSTRAINT "ACT_FK_TASK_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;

ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_BYTEARRAY" FOREIGN KEY ("BYTEARRAY_ID_")
REFERENCES "ONEASSIST_SP"."ACT_GE_BYTEARRAY" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_EXE" FOREIGN KEY ("EXECUTION_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
ALTER TABLE "ONEASSIST_SP"."ACT_RU_VARIABLE" ADD CONSTRAINT "ACT_FK_VAR_PROCINST" FOREIGN KEY ("PROC_INST_ID_")
REFERENCES "ONEASSIST_SP"."ACT_RU_EXECUTION" ("ID_") ENABLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_EVT_LOG TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_EVT_LOG FOR ONEASSIST_SP.ACT_EVT_LOG;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_GE_BYTEARRAY TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_GE_BYTEARRAY FOR ONEASSIST_SP.ACT_GE_BYTEARRAY;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_GE_PROPERTY TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_GE_PROPERTY FOR ONEASSIST_SP.ACT_GE_PROPERTY;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_ACTINST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_ACTINST FOR ONEASSIST_SP.ACT_HI_ACTINST;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_ATTACHMENT TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_ATTACHMENT FOR ONEASSIST_SP.ACT_HI_ATTACHMENT;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_COMMENT TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_COMMENT FOR ONEASSIST_SP.ACT_HI_COMMENT;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_DETAIL TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_DETAIL FOR ONEASSIST_SP.ACT_HI_DETAIL;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_IDENTITYLINK TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_IDENTITYLINK FOR ONEASSIST_SP.ACT_HI_IDENTITYLINK;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_PROCINST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_PROCINST FOR ONEASSIST_SP.ACT_HI_PROCINST;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_TASKINST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_TASKINST FOR ONEASSIST_SP.ACT_HI_TASKINST;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_HI_VARINST TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_HI_VARINST FOR ONEASSIST_SP.ACT_HI_VARINST;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_ID_GROUP TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_ID_GROUP FOR ONEASSIST_SP.ACT_ID_GROUP;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_ID_INFO TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_ID_INFO FOR ONEASSIST_SP.ACT_ID_INFO;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_ID_MEMBERSHIP TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_ID_MEMBERSHIP FOR ONEASSIST_SP.ACT_ID_MEMBERSHIP;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_ID_USER TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_ID_USER FOR ONEASSIST_SP.ACT_ID_USER;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RE_DEPLOYMENT TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RE_DEPLOYMENT FOR ONEASSIST_SP.ACT_RE_DEPLOYMENT;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RE_MODEL TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RE_MODEL FOR ONEASSIST_SP.ACT_RE_MODEL;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RE_PROCDEF TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RE_PROCDEF FOR ONEASSIST_SP.ACT_RE_PROCDEF;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_EVENT_SUBSCR TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_EVENT_SUBSCR FOR ONEASSIST_SP.ACT_RU_EVENT_SUBSCR;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_EXECUTION TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_EXECUTION FOR ONEASSIST_SP.ACT_RU_EXECUTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_IDENTITYLINK TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_IDENTITYLINK FOR ONEASSIST_SP.ACT_RU_IDENTITYLINK;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_JOB TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_JOB FOR ONEASSIST_SP.ACT_RU_JOB;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_TASK TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_TASK FOR ONEASSIST_SP.ACT_RU_TASK;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_VARIABLE TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_VARIABLE FOR ONEASSIST_SP.ACT_RU_VARIABLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST_SP.ACT_RU_VARIABLE TO ONEASSIST_DML_SP;
CREATE OR REPLACE SYNONYM oneassist_sp_app.ACT_RU_VARIABLE FOR ONEASSIST_SP.ACT_RU_VARIABLE;

alter table ONEASSIST_SP.oa_service_request_dtl add (asset_id number(20,0), cust_id number(10,0)); 

CREATE TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" 
   (	"KEYSET_ID" NUMBER(10,0), 
	"KEYSET_NAME" VARCHAR2(50 BYTE), 
	"KEYSET_DESCRIPTION" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'A', 
	"CREATED_ON" TIMESTAMP (6) DEFAULT systimestamp, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(20 BYTE)
   ) ;

   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."KEYSET_ID" IS 'PK of this table';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."KEYSET_NAME" IS 'Name of the key set. For e.g. SR_FEEDBACK_CODES or INSP_CANC_REASON';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."KEYSET_DESCRIPTION" IS 'Description about the key set';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."STATUS" IS 'A means active, X means cancelled / deleted';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."CREATED_ON" IS 'Creation date time of the record';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."CREATED_BY" IS 'User id who created it';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."MODIFIED_ON" IS 'Updation date time of the record';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST"."MODIFIED_BY" IS 'User id who updated it';
REM INSERTING into ONEASSIST_SP.OA_GENERIC_KEYSET_MST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index OA_GENERIC_KEYSET_MST_INDEX1
--------------------------------------------------------

  CREATE INDEX "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST_INDEX1" ON "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" ("KEYSET_ID");
--------------------------------------------------------
--  DDL for Index OA_GENERIC_KEYSET_MST_INDEX2
--------------------------------------------------------

  CREATE INDEX "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST_INDEX2" ON "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" ("KEYSET_NAME");
--------------------------------------------------------
--  Constraints for Table OA_GENERIC_KEYSET_MST
--------------------------------------------------------

  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" MODIFY ("KEYSET_ID" NOT NULL ENABLE);
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" ADD CONSTRAINT "OA_GENERIC_KEYSET_MST_UK1" UNIQUE ("KEYSET_NAME");
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_MST" ADD CONSTRAINT "OA_GENERIC_KEYSET_MST_PK" PRIMARY KEY ("KEYSET_ID");
  
  
  
  --------------------------------------------------------
--  File created - Friday-October-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OA_GENERIC_KEYSET_VALUE_DTL
--------------------------------------------------------

  CREATE TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" 
   (	"VALUE_ID" NUMBER(10,0), 
	"KEYSET_ID" NUMBER(10,0), 
	"KEY" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'A', 
	"CREATED_ON" TIMESTAMP (6) DEFAULT systimestamp, 
	"CREATED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(20 BYTE)
   ) ;

   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."VALUE_ID" IS 'PK of this table';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."KEYSET_ID" IS 'FK (OA_GENERICKEY_MST.KEYSET_ID)';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."KEY" IS 'Unique within the keyset. This value will be used by the system ONLY. Should not be exposed to end user / customer';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."VALUE" IS 'Value of the key. This value will appear on the UI';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."STATUS" IS 'A means active, X means cancelled / deleted';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."CREATED_ON" IS 'Creation date time of the record';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."CREATED_BY" IS 'User id who created it';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."MODIFIED_ON" IS 'Updation date time of the record';
   COMMENT ON COLUMN "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL"."MODIFIED_BY" IS 'User id who updated it';
REM INSERTING into ONEASSIST_SP.OA_GENERIC_KEYSET_VALUE_DTL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index OA_GENERIC_KEYSET_VALUE_D_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_D_UK1" ON "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" ("KEYSET_ID", "KEY") ;
--------------------------------------------------------
--  DDL for Index OA_GENERIC_KEYSET_VALUE_DT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DT_PK" ON "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" ("VALUE_ID");
--------------------------------------------------------
--  Constraints for Table OA_GENERIC_KEYSET_VALUE_DTL
--------------------------------------------------------

  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" MODIFY ("KEYSET_ID" NOT NULL ENABLE);
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" MODIFY ("VALUE_ID" NOT NULL ENABLE);
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" ADD CONSTRAINT "OA_GENERIC_KEYSET_VALUE_D_UK1" UNIQUE ("KEYSET_ID", "KEY");
  ALTER TABLE "ONEASSIST_SP"."OA_GENERIC_KEYSET_VALUE_DTL" ADD CONSTRAINT "OA_GENERIC_KEYSET_VALUE_DT_PK" PRIMARY KEY ("VALUE_ID");

  
  CREATE SEQUENCE "ONEASSIST_SP".SEQ_OA_GENERIC_KEYSET_MST
 START WITH     1000
 INCREMENT BY   1;
 
 CREATE SEQUENCE "ONEASSIST_SP".SEQ_OA_GENERIC_KEYSET_VALUE
 START WITH     1000
 INCREMENT BY   1;
 
 
alter table ONEASSIST_SP.oa_service_request_dtl add (ACTUAL_START_DATETIME TIMESTAMP(6));
alter table ONEASSIST_SP.oa_service_request_dtl add (ACTUAL_END_DATETIME TIMESTAMP(6));
alter table ONEASSIST_SP.OA_SERVICE_REQUEST_DTL add (FEEDBACK_CODE VARCHAR2(10));
alter table ONEASSIST_SP.OA_SERVICE_REQUEST_DTL add (FEEDBACK_RATING NUMBER(1));
alter table ONEASSIST_SP.OA_SERVICE_REQUEST_DTL add (FEEDBACK_COMMENTS VARCHAR2(300));
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL RENAME COLUMN SERVICE_SCHEDULE_STARTTIME TO SCHEDULE_SLOT_START_DATETIME;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL RENAME COLUMN SERVICE_SCHEDULE_ENDTIME TO SCHEDULE_SLOT_END_DATETIME;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL RENAME COLUMN SERVICE_DUEDATETIME TO DUE_DATETIME;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_TASK_MST RENAME COLUMN PROD_CODE TO REFERENCE_CODE;