ALTER TABLE ONEASSIST_SP.OA_SHIPMENT_DOC_DTL DROP COLUMN SHIPMENT_ID;
ALTER TABLE ONEASSIST_SP.oa_service_doc_dtl DROP COLUMN SHIPMENT_DOC_KEY;

ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN IS_SELF_REPAIR;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN PLAN_CODE;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN PLAN_PURCHASE_DATE;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN CUST_ID;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN ASSET_ID;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN REQUEST_RAISED_BY;
ALTER TABLE ONEASSIST_SP.OA_SERVICE_REQUEST_DTL DROP COLUMN REQUEST_RAISED_FROM;
alter table ONEASSIST_SP.OA_SERVICE_REQUEST_DTL drop column PROD_CODE;