CREATE TABLE ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST
(
PRODUCT_VARIANT_ID NUMBER(10,0) NOT NULL,
ITEM_NAME VARCHAR2(50 BYTE) NOT NULL,
ITEM_DESCRIPTION VARCHAR2(300 BYTE),
PRODUCT_TECHNOLOGY VARCHAR2(50 BYTE),
PRODUCT_SIZE NUMBER(10,0),
PROD_CODE VARCHAR2(20 BYTE),
PRODUCT_UNIT VARCHAR2(20),
STATUS VARCHAR2(1 BYTE),
CREATED_DATE TIMESTAMP,
CREATED_BY VARCHAR2(200 BYTE),
MODIFIED_DATE TIMESTAMP,
MODIFIED_BY VARCHAR2(200 BYTE));
COMMENT ON TABLE ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST IS 'This table is used to map product with the technology';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.PRODUCT_VARIANT_ID IS 'PK';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.ITEM_NAME IS 'Name of product variant';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.ITEM_DESCRIPTION IS 'Description about product variant';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.PRODUCT_TECHNOLOGY IS 'Technology of the product such as LED, LCD, CURVE';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.PRODUCT_SIZE IS '32,40';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.PROD_CODE IS 'product code such as MP,TE,TP';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.PRODUCT_UNIT IS 'product unit';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.STATUS IS 'Status of product variant i.e A-Active/X-Inactive';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.CREATED_DATE IS 'record created date';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.CREATED_BY IS 'record created by';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.MODIFIED_DATE IS 'record modifed date';
COMMENT ON COLUMN ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST.MODIFIED_BY IS 'record modified by';
ALTER TABLE ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST ADD CONSTRAINT PRODUCT_VARIANT_ID_PK PRIMARY KEY (PRODUCT_VARIANT_ID) ENABLE;
ALTER TABLE ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST ADD FOREIGN KEY (PROD_CODE) REFERENCES ONEASSIST.OA_PRODUCT_MST (PROD_CODE) ENABLE;

CREATE SEQUENCE ONEASSIST.OA_SER_PROD_VARIANT_MST_SEQ INCREMENT BY 1 MAXVALUE 999999999999 MINVALUE 1 NOCACHE ORDER;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST TO ONEASSIST_DML_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST TO ONEASSIST_READ_ROLE;
CREATE OR REPLACE SYNONYM OASYS.OA_SERVICE_PRODUCT_VARIANT_MST FOR ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST;
GRANT SELECT ON ONEASSIST.OA_SER_PROD_VARIANT_MST_SEQ TO ONEASSIST_DML_ROLE;
GRANT SELECT ON ONEASSIST.OA_SER_PROD_VARIANT_MST_SEQ TO ONEASSIST_READ_ROLE;
CREATE OR REPLACE SYNONYM OASYS.OA_SER_PROD_VARIANT_MST_SEQ FOR ONEASSIST.OA_SER_PROD_VARIANT_MST_SEQ;
------------------------------- OA_SERVICE_PRODUCT_VARIANT_MST ENDS--------------------------
ALTER TABLE ONEASSIST.OA_CUSTOMER_HOMEAPPLIANCE_DTL ADD PRODUCT_VARIANT_ID NUMBER(10,0);
ALTER TABLE ONEASSIST.OA_CUSTOMER_HOMEAPPLIANCE_DTL ADD FOREIGN KEY (PRODUCT_VARIANT_ID) REFERENCES ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID) ENABLE;
ALTER TABLE ONEASSIST.oa_customer_homeappliance_hst ADD PRODUCT_VARIANT_ID NUMBER(10,0);
------------------------------- OA_SERVICE_PRODUCT_VARIANT_MST ENDS--------------------------
CREATE TABLE ONEASSIST.OA_PARTNER_BU_HUB_RLN(PARTNER_BU_CODE NUMBER(5),HUB_ID NUMBER(12),SRV_CNTR_BRAND_NAME VARCHAR2(20));

ALTER TABLE ONEASSIST.OA_PARTNER_BU_HUB_RLN ADD CONSTRAINT FK_PARTNER_BU_ID FOREIGN KEY (PARTNER_BU_CODE) REFERENCES ONEASSIST.OA_PARTNER_BU_MST (PARTNER_BU_CODE) ENABLE;

ALTER TABLE ONEASSIST.OA_PARTNER_BU_HUB_RLN ADD CONSTRAINT FK_HUB_ID FOREIGN KEY (HUB_ID) REFERENCES ONEASSIST.OA_CLAIM_HUB_MST (HUB_ID_PK) ENABLE;
ALTER TABLE ONEASSIST.OA_PARTNER_BU_HUB_RLN ADD CONSTRAINT PK_PARTNER_BU_HUB_ID PRIMARY KEY (PARTNER_BU_CODE,HUB_ID) USING INDEX ENABLE;

GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST.OA_PARTNER_BU_HUB_RLN TO ONEASSIST_DML_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON ONEASSIST.OA_PARTNER_BU_HUB_RLN TO ONEASSIST_READ_ROLE;
CREATE OR REPLACE SYNONYM OASYS.OA_PARTNER_BU_HUB_RLN FOR ONEASSIST.OA_PARTNER_BU_HUB_RLN;
----------------------------------------------------------------------------------------

ALTER TABLE ONEASSIST.OA_PARTNER_USR_DTL ADD (PROFILE_IMAGE_STORAGE_REF_ID VARCHAR2(64),MOBILE_NO1 NUMBER(10),EXPERIENCE NUMBER(14,2));
ALTER TABLE ONEASSIST.oa_partner_usr_dtl_hst ADD (BU_CODE NUMBER(5),PROFILE_IMAGE_STORAGE_REF_ID VARCHAR2(64),MOBILE_NO1 NUMBER(10),EXPERIENCE NUMBER(14,2));
------------------------------
---trigger
create or replace
TRIGGER ONEASSIST.OA_PRTNR_USR_DTL_HST_BUTRG BEFORE UPDATE ON ONEASSIST.OA_PARTNER_USR_DTL for each row
BEGIN
insert into ONEASSIST.OA_PARTNER_USR_DTL_HST values (
:old.PARTNER_USERID,
:old.PARTNER_CODE,
:old.USER_FIRSTNAME,
:old.USER_MIDDLENAME,
:old.USER_LASTNAME,
:old.USER_EMAILID,
:old.LL_NO,
:old.MOBILE_NO,
:old.AUTH_BY,
:old.AUTH_DATE,
:old.CREATED_BY,
:old.CREATED_DATE,
:old.MODIFIED_BY,
:old.MODIFIED_DATE,
:old.STATUS,
:old.BU_CODE,
:old.PASSKEY,
:old.PROFILE_IMAGE_STORAGE_REF_ID,
:old.MOBILE_NO1,
:old.EXPERIENCE);
END;
/