-----OASYS SCRIPTS------------------------

SET DEFINE OFF;
------------------------------- OA_SERVICE_PRODUCT_VARIANT_MST STARTS--------------------------


--To insert into product_variant_mst
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Panel TV','Panel TV','Less than or Equal To 32"',0,'TV','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Panel TV','Panel TV','Greater than 32"',0,'TV','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Refrigerator','Refrigerator','DC',0,'REF','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Refrigerator','Refrigerator','Double Door',0,'REF','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Refrigerator','Refrigerator','SBS',0,'REF','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Washers','Washers','Semi Auto',0,'WM','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Washers','Washers','Top Load Fully',0,'WM','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Washers','Washers','Front load Fully',0,'WM','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'AC','AC','Window AC',0,'AC','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'AC','AC','Split AC',0,'AC','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Dryer','Dryer','Dryer',0,'DRY','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Microwave','Microwave','Solo',0,'MW','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Microwave','Microwave','Grill',0,'MW','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Microwave','Microwave','Convection',0,'MW','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'OTG','OTG','',0,'FRY','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Geysers/Water Heaters','Geysers/Water Heaters','',0,'WHEAT','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');
INSERT INTO ONEASSIST.OA_SERVICE_PRODUCT_VARIANT_MST (PRODUCT_VARIANT_ID,ITEM_NAME,ITEM_DESCRIPTION,PRODUCT_TECHNOLOGY,PRODUCT_SIZE,PROD_CODE,STATUS, CREATED_DATE, CREATED_BY,MODIFIED_DATE, MODIFIED_BY ) VALUES (OA_SER_PROD_VARIANT_MST_SEQ.nextval,'Water Purifier','Water Purifier','',0,'WPUR','A', CURRENT_TIMESTAMP,'ADMIN', CURRENT_TIMESTAMP, 'ADMIN');

--HA CLAIMS role to admin user

Insert into oneassist.oa_function_perms_mst (FUNC_PERM_ID,FUNC_PERM_NAME,USER_TYPE,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,DESCP,STATUS)
values (2176,'HA Claims',null,'SCRIPT',SYSDATE,'SCRIPT',SYSDATE,null,SYSDATE,'HA Claims processing','A');

Insert into oneassist.oa_role_mst (ROLE_ID,ROLE_NAME,ROLE_DESC,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,APP_ID)
values (1055,'HA Claims Role','HA Claims Processing','SCRIPT',SYSDATE,'SCRIPT',SYSDATE,null,null,'A',null);

Insert into oneassist.oa_role_funcperm_dtl (ROLE_ID,FUNC_PERM_ID,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE)
values (1055,2176,'SCRIPT',SYSDATE,'SCRIPT',SYSDATE,null,SYSDATE);

Insert into oneassist.oa_system_config
(PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE)
values ('SERVICE_PLATFORM_URL','PROCESS_SLA_BREACH_URL','http://10.20.1.84/serviceplatform/api/servicerequests/processServiceRepairRequestSLABreach','A',null,null,'admin@ONEASSIST.in',sysdate,null,sysdate,'N',null,'NA');

---batch url--


Insert into ONEASSIST.OA_BATCH_CONFIG (BATCH_ID,NAME,DES,LAST_RUN_DT,NEXT_RUN_DT,TIME,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,RESCHEDULING_REQUIRED) values (1088,'ServicePlatform SLA Breach Batch','ServicePlatform SLA Breach Batch',sysdate,sysdate,'1','admin@oneassist.in',sysdate,'admin@oneassist.in',sysdate,'0','NO');
--service center system config
Insert into ONEASSIST.OA_SYSTEM_CONFIG(PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('industry','SERVICE CENTER','SERVICE CENTER','A','script',sysdate,'script',sysdate,null,null,'N',null,'NA');
Insert into ONEASSIST.OA_SYSTEM_CONFIG(PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE CENTER','SERVICE_CENTER','SERVICE CENTER','A','script',sysdate,'script',sysdate,'script',sysdate,'U',null,'PartnerTypeMst');
Insert into ONEASSIST.OA_SYSTEM_CONFIG(PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_CENTER','SERVICE_CENTER','SERVICE_CENTER','A','script',sysdate,'script',sysdate,null,null,'N',null,'UnitTypeMst');
commit;
----Insert into EXPORT_TABLE --(ROLE_ID,ROLE_NAME,ROLE_DESC,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,APP_ID) values --(1015,'HA Claims Role','HA Claims Processing','SCRIPT',to_date('01-AUG-17 11.59.07','DD-MON-RR --HH.MI.SS'),'SCRIPT',to_timestamp('01-AUG-17 11.59.07.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,'A',null);

--service center and partner insertion
Insert into ONEASSIST.oa_partner_mst (PARTNER_CODE,PARTNER_TYPE,PARTNER_NAME,CITY,CORPORATE_EMAIL_ID,CORPORATE_LL_NO,CORPORATE_MOBILE_NO,CORPORATE_FAX_NO,PARTNER_STATUS,CONTACT_PERSON_NAME,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,ALT_CORPORATE_EMAILID,COMPANY_CODE,COMPANY_NAME,SRC_CHANNEL_CODE,LINE1,LINE2,LANDMARK,STATE,PINCODE,INDUSTRY,BUSINESS_PARTNER_TYPE) 
values (92,'1','SERVICE CENTER','MC',null,null,null,null,'A',null,'SCRIPT',sysdate,'SCRIPT',sysdate,null,null,null,'SERVICE_CENTER',null,'RTL',null,null,null,'MH','400059','SERVICE CENTER','SERVICE_CENTER');
Insert into ONEASSIST.oa_partner_bu_mst (PARTNER_BU_CODE,PARTNER_CODE,BU_CODE,BU_NAME,CORPORATE_EMAILID,CORPORATE_ALT_EMAILID,CORPORATE_LL_NO,CORPORATE_MOBILE_NO,CORPORATE_FAX_NO,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,LINE1,LINE2,LANDMARK,STATE,CITY,PINCODE,INDUSTRY,BUSINESS_UNIT_TYPE) 
values (1344,92,null,'LG MUMBAI','servicecenter1@mail.com',null,null,1234554321,null,'A','SCRIPT',sysdate,'SCRIPT',sysdate,null,null,null,null,'Mumbai','MH','MCS','400059',null,'SERVICE_CENTER');
Insert into ONEASSIST.oa_partner_usr_dtl (PARTNER_USERID,PARTNER_CODE,USER_FIRSTNAME,USER_MIDDLENAME,USER_LASTNAME,USER_EMAILID,LL_NO,MOBILE_NO,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,BU_CODE,PASSKEY,PROFILE_IMAGE_STORAGE_REF_ID,MOBILE_NO1,EXPERIENCE) 
values (10360669,92,'Service center',null,'user','servicecenter1@mail.com',null,1234554321,null,null,'ADMIN',sysdate,null,null,'A',1344,'TddqH5J6m0ZFedyeix9ILqDKm3fiFb37MLMtktf2Aww%3D',null,null,null);

Insert into ONEASSIST.oa_user_login_info (USER_ID,USER_TYPE,LAST_LOGIN_DATE,LAST_LOGIN_IP,CURRENT_LOGIN_IP,CURRENT_LOGIN_DATE,PREVIOUS_PASS,SECRET_QTN_CODE,SECRET_QTN_ANS,USER_LOGIN_ID,USER_PASS,WRONG_PASS_COUNT,FORGOTPASS_LASTDATE,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,USER_PASS_LOCK,PASSWORD_EXPIRE,PASS_EXPIRY,CHANGE_PASS,STATUS,RESET_LINK_EXPIRY,RESET_LINK_STATUS,WRONG_SECRET_COUNT,DOCUSAFE_LOCK,INITIATING_SYS)
values (10360669,'WebServiceUnit',sysdate,null,null,sysdate,'9WCb48BhCz7VgRyGxdcGNNpbUp8=',null,null,'servicecenter1@mail.com','SKzrGoLPHhopFewEEDaec8+tM/E=',0,null,null,null,'ADMIN',sysdate,'SCRIPT',sysdate,0,sysdate,null,'N','A',sysdate,0,null,null,10017904);
------------------------------------------

--Servce center migration script to partner bu mst--
SELECT * FROM OA_CLAIM_SRV_CNTR_MST;
UPDATE ONEASSIST.OA_CLAIM_SRV_CNTR_MST SET SRV_CNTR_STATE=ONEASSIST.PARTNERBU_SEQ.NEXTVAL;


INSERT INTO ONEASSIST.OA_PARTNER_BU_MST (PARTNER_BU_CODE,PARTNER_CODE,BU_CODE,BU_NAME,CORPORATE_EMAILID,
CORPORATE_ALT_EMAILID,CORPORATE_LL_NO,CORPORATE_MOBILE_NO,CORPORATE_FAX_NO,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,
MODIFIED_BY,MODIFIED_DATE,LINE1,LINE2,LANDMARK,STATE,CITY,PINCODE,INDUSTRY,BUSINESS_UNIT_TYPE) SELECT SRV_CNTR_STATE,
(SELECT PARTNER_CODE FROM OA_PARTNER_MST where partner_type=1 and partner_name='SERVICE CENTER' and business_partner_type='SERVICE_CENTER'),null,SRV_CNTR_NAME,SRV_CNTR_EMAIL,
null,null,SRV_CNTR_MOBILE,null,'A',SRV_CNTR_MODIFIED_BY,SRV_CNTR_MODIFIED_DATE,SRV_CNTR_CREATED_BY,
SRV_CNTR_CREATED_DATE,null,null,SRV_CNTR_ADDRESS,null,null,NULL,SRV_CNTR_CITY,
null,null,'SERVICE_CENTER' FROM ONEASSIST.OA_CLAIM_SRV_CNTR_MST;

INSERT INTO ONEASSIST.OA_PARTNER_BU_HUB_RLN (PARTNER_BU_CODE, HUB_ID, SRV_CNTR_BRAND_NAME) SELECT SRV_CNTR_STATE,HUB_ID,SRV_CNTR_BRAND_NAME FROM ONEASSIST.OA_CLAIM_SRV_CNTR_MST;

update ONEASSIST.OA_CLAIM_DTL CLAIMS
set (CLAIMS.SERVICE_CNTR_ID) = (select SRV_CNTR.SRV_CNTR_STATE
from ONEASSIST.OA_CLAIM_SRV_CNTR_MST SRV_CNTR
where CLAIMS.SERVICE_CNTR_ID = SRV_CNTR.SRV_CNTR_ID_PK);

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','5','19:00-21:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'N',null,'NA');

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','4','17:00-19:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate),'N',null,'NA');

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','3','15:00-17:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate),'N',null,'NA');

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','2','13:00-15:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate),'N',null,'NA');

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','1','11:00-13:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate),'N',null,'NA');

Insert into oneassist.OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('SERVICE_INSPECT_SLOT','0','09:00-11:00','A','OASYSADMIN',sysdate,'OASYSADMIN',sysdate,'OASYSADMIN',sysdate),'N',null,'NA');

COMMIT;