ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;
ALTER TABLE OA_SERVICE_DOC_DTL ADD (DOC_ID_TEMP VARCHAR2(100 BYTE));
UPDATE OA_SERVICE_DOC_DTL SET DOC_ID_TEMP = DOC_ID;
ALTER TABLE OA_SERVICE_DOC_DTL DROP COLUMN DOC_ID;
ALTER TABLE OA_SERVICE_DOC_DTL RENAME COLUMN DOC_ID_TEMP TO DOC_ID;


ALTER TABLE OA_SERVICE_DOC_DTL
ADD CONSTRAINT DOC_TYPE_FK FOREIGN KEY (DOC_TYPE_ID) 
REFERENCES OA_DOC_TYPE_MST(DOC_TYPE_ID);

ALTER TABLE OA_SERVICE_DOC_DTL MODIFY FILE_NAME VARCHAR2(100 BYTE);
