ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

DELETE FROM OA_GENERIC_KEYSET_VALUE_DTL WHERE KEYSET_ID = SELECT KEYSET_ID FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('WORKFLOW_STAGE_STATUS','SERVICE_REQUEST_STATUS','WORKFLOW_ALERT','SFTP_LOCATION','PARTNER_STAGE_STATUS_DEFAULTS', 'HA_FR_ACTIVITI_VARIABLES','HA_BR_ACTIVITI_VARIABLES','HA_AD_ACTIVITI_VARIABLES','HA_BD_ACTIVITI_VARIABLES', 'HA_EW_ACTIVITI_VARIABLES');
DELETE FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('WORKFLOW_STAGE_STATUS', 'SERVICE_REQUEST_STATUS','WORKFLOW_ALERT','SFTP_LOCATION','PARTNER_STAGE_STATUS_DEFAULTS', 'HA_FR_ACTIVITI_VARIABLES','HA_BR_ACTIVITI_VARIABLES','HA_AD_ACTIVITI_VARIABLES','HA_BD_ACTIVITI_VARIABLES', 'HA_EW_ACTIVITI_VARIABLES');


DELETE FROM OA_GENERIC_KEYSET_VALUE_DTL WHERE KEYSET_ID = SELECT KEYSET_ID FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('HA_CLAIMS_SHORT_CIRCUIT_REASON');
DELETE FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('HA_CLAIMS_SHORT_CIRCUIT_REASON');