INSERT INTO ONEASSIST_SP.OA_GENERIC_KEYSET_VALUE_DTL (VALUE_ID, KEYSET_ID, KEY, VALUE, CREATED_BY)
VALUES (SEQ_OA_GENERIC_KEYSET_VALUE.nextval, (select KEYSET_ID FROM OA_GENERIC_KEYSET_MST WHERE OA_GENERIC_KEYSET_MST.KEYSET_NAME = 'SFTP_LOCATION'), 'WHC_CLAIM_FORM', '/home/ec2-user/Template_WHC_Claim_Form.doc', 'admin');

COMMIT;