ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST;

DELETE FROM OA_SYSTEM_CONFIG WHERE PARAM_CODE='PartnerStatus' AND PARAM_TYPE IN ('DHL_PICKUP','DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','198','PUF','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','405','INT','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','560','DEL','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','310','INT','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','200','PUD','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','150','ASG','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','408','EXC','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_PICKUP');




Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','198','PUF','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','405','INT','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','560','DEL','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','310','INT','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','200','PUD','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','150','ASG','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');

Insert into OA_SYSTEM_CONFIG (PARAM_CODE,PARAM_NAME,PARAM_VALUE,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,EVENT,REJECT_REASON,PARAM_TYPE) values ('PartnerStatus','408','EXC','A','ADMIN',SYSDATE,'OASYSADMIN',SYSDATE,null,null,'N',null,'DHL_REVERSE_PICKUP');
COMMIT;

ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

UPDATE  OA_SERVICE_REQUEST_DTL SET MODIFIED_ON = CREATED_ON,MODIFIED_BY = 'SCRIPT' WHERE MODIFIED_ON IS NULL AND STATUS IN ('CO','X','C');
COMMIT;