ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'DW');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'DW');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'KC');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'KC');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'MW');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'MW');


Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'MP01');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'MP01');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'AC');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'AC');


Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'OTG');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'OTG');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'FDPR');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'FDPR');


Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'WM');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'WM');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'WAPUR');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'WAPUR');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'WHEAT');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'WHEAT');


Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'ACOOL');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'ACOOL');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'VAC');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'VAC');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'APUR');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'APUR');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'DRY');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'DRY');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'REF');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'REF');

Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1005','Y','A','ADMIN',SYSDATE,'TV');
Insert into OA_SERVICE_CONFIG (ID,SERVICE_CODE,CONFIG_KEY,PARAM_NAME,PARAM_VALUE,STATUS,CREATED_BY,CREATED_ON,PARAM_TYPE) values (SEQ_OA_SERVICE_CONFIG.NEXTVAL,'WHC_INSPECTION','DOCUMENT_CONFIG','1006','Y','A','ADMIN',SYSDATE,'TV');

COMMIT;