ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

DROP TABLE OA_SERV_REQ_STAGE_MST;
DROP TABLE OA_SERV_REQ_STAGE_STATUS_MST;
DROP TABLE OA_SERV_REQ_TRANSITION_CONFIG;

DROP SEQUENCE  "SEQ_OA_SERV_REQ_STAGE_MST";
DROP SEQUENCE  "SEQ_OA_SERV_REQ_TRANS_CONFIG";
DROP SEQUENCE  "SEQ_OA_SERV_REQ_STG_STATUS_MST";

