ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

DELETE FROM OA_GENERIC_KEYSET_VALUE_DTL WHERE KEYSET_ID = SELECT KEYSET_ID FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('WORKFLOW_STAGE_STATUS','SERVICE_REQUEST_STATUS');
DELETE FROM OA_GENERIC_KEYSET_MST WHERE KEYSET_NAME IN ('WORKFLOW_STAGE_STATUS', 'SERVICE_REQUEST_STATUS');