package com.oneassist.serviceplatform.commons.enums;

public enum ErrorCodes {
    SYS_CREATE_PINCODESERVICE_FAILED(1000),
    INVALID_INPUT_DATA(10001),
    UNABLE_SAVE_PINCODE_SERVICE(10002),
    UNABLE_SAVE_PINCODE_SERVICE_FULFILMENT(10003),
    INVALID_PINCODE(10004),
    INVALID_PARTNER_CODE(10005),
    INVALID_SERVICE_TYPE(10006),
    INVALID_HUB_ID(10007),
    INVALID_COURTESY_FLAG(10008),
    INVALID_VENDOR_TAT(10009),
    UNABLE_LOAD_CACHE_FACTORY(10010),
    PINCODESERVICE_EXCEPTION(10011),
    PINCODESERVICEFULFILMENT_EXCEPTION(10012),
    UNABLE_GET_SERVICE_TYPE(10016),
    INVALID_PRODUCT_CODE(30070),
    INVALID_PARTNER_BU_CODE(30071);

    private final int errorCode;

    ErrorCodes(int errorCode) {

        this.errorCode = errorCode;
    }

    public int getErrorCode() {

        return this.errorCode;
    }
}
