package com.oneassist.serviceplatform.commons.enums;

public enum ServiceRequestEventCode {

    COMPLETE_DOCUMENT_UPLOAD_SELFREPAIR("COMPLETE_DOCUMENT_UPLOAD_SELFREPAIR", "SELFREPAIR"),
    CUSTOMER_RESCHEDULE_VISIT("CUSTOMER_RESCHEDULE_VISIT", "NON-SELFREPAIR"),
    IC_DECISION_REJECTED("IC_DECISION_REJECTED", "NON-SELFREPAIR"),
    ESTIMATED_INVOICE_VERIFICATION_FAIL("ESTIMATED_INVOICE_VERIFICATION_FAIL", "SELFREPAIR"),
    COMPLETE_DOCUMENT_UPLOAD("COMPLETE_DOCUMENT_UPLOAD", "NON-SELFREPAIR"),
    INSPECTION_SR_EXPIRED("INSPECTION_SR_EXPIRED", "NON-SELFREPAIR"),
    CREATE_INSPECT_SR_ALLOCATE_SC("CREATE_INSPECT_SR_ALLOCATE_SC", "NON-SELFREPAIR"),
    INSPECTION_COMPLETED("INSPECTION_COMPLETED", "NON-SELFREPAIR"),
    CREATE_INSPECT_SR_SC_NOTALLOCATED("CREATE_INSPECT_SR_SC_NOTALLOCATED"),
    TECHNICIAN_AT_LOCATION_AND_BEGINS_SERVICE("TECHNICIAN_AT_LOCATION_AND_BEGINS_SERVICE", "NON-SELFREPAIR"),
    CUSTOMER_CAN_WAIT_FURTHER("CUSTOMER_CAN_WAIT_FURTHER", "NON-SELFREPAIR"),
    TECHNICIAN_CANCEL_INSPECTION_CUSTOMER_NOT_AVAILABLE("TECHNICIAN_CANCEL_INSPECTION_CUSTOMER_NOT_AVAILABLE", "NON-SELFREPAIR"),
    ALLOCATE_TECH_INSPECT("ALLOCATE_TECH_INSPECT", "NON-SELFREPAIR"),
    IC_DECISION_APPROVED("IC_DECISION_APPROVED", "NON-SELFREPAIR"),
    REPAIR_SERVICE_RESCHEDULED_IC_APPROVED("REPAIR_SERVICE_RESCHEDULED_IC_APPROVED", "NON-SELFREPAIR"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_VISIT("CREATE_SERVICE_SERVICEABLE_PINCODE_VISIT"),
    IC_DECISION_BER_APPROVED_SELF_REPAIR("IC_DECISION_BER_APPROVED_SELF_REPAIR", "SELFREPAIR"),
    INVOICE_VERIFICATION_SUCCESS_SELFREPAIR("INVOICE_VERIFICATION_SUCCESS_SELFREPAIR", "SELFREPAIR"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_VERIFICATION_SELFREPAIR("CREATE_SERVICE_SERVICEABLE_PINCODE_VERIFICATION_SELFREPAIR"),
    CUSTOMER_CANCELS_INSPECTION("CUSTOMER_CANCELS_INSPECTION", "NON-SELFREPAIR"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_VERIFICATION("CREATE_SERVICE_SERVICEABLE_PINCODE_VERIFICATION"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_DOCUPLOAD("CREATE_SERVICE_SERVICEABLE_PINCODE_DOCUPLOAD"),
    INVOICE_VERIFICATION_FAIL_SELFREPAIR("INVOICE_VERIFICATION_FAIL_SELFREPAIR", "SELFREPAIR"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_VISIT_SELFREPAIR("CREATE_SERVICE_SERVICEABLE_PINCODE_VISIT_SELFREPAIR"),
    IC_APPROVAL_WAITING_WITH_SPARE_NEEDED("IC_APPROVAL_WAITING_WITH_SPARE_NEEDED", "NON-SELFREPAIR"),
    IC_APPROVAL_WAITING_WITH_TRANSPORTATION_NEEDED("IC_APPROVAL_WAITING_WITH_TRANSPORTATION_NEEDED", "NON-SELFREPAIR"),
    HA_AD_RESCHEDULE_AFTER_CUSTOMER_PAYMENT("HA_AD_RESCHEDULE_AFTER_CUSTOMER_PAYMENT", "NON-SELFREPAIR"),
    TECHNICIAN_CANCEL_INSPECTION_FOR_SOME_REASON("TECHNICIAN_CANCEL_INSPECTION_FOR_SOME_REASON", "NON-SELFREPAIR"),
    INSPECTION_STARTED("INSPECTION_STARTED", "NON-SELFREPAIR"),
    CUSTOMER_RESCHEDULE_VISIT_POST_TECHNICIAN_ALLOCATION("CUSTOMER_RESCHEDULE_VISIT_POST_TECHNICIAN_ALLOCATION", "NON-SELFREPAIR"),
    REPAIR_SERVICE_RESCHEDULED_SPARE_AVAILABLE("REPAIR_SERVICE_RESCHEDULED_SPARE_AVAILABLE", "NON-SELFREPAIR"),
    COMPLETED_AFTER_REPAIR_ASSESSMENT("COMPLETED_AFTER_REPAIR_ASSESSMENT", "NON-SELFREPAIR"),
    CUSTOMER_ASKS_REFUND("CUSTOMER_ASKS_REFUND", "NON-SELFREPAIR"),
    ESTIMATED_INVOICE_VERIFICATION_SUCCESS("ESTIMATED_INVOICE_VERIFICATION_SUCCESS", "SELFREPAIR"),
    INVOICE_VERIFICATION_FAIL("INVOICE_VERIFICATION_FAIL", "NON-SELFREPAIR"),
    CREATE_SERVICE_SERVICEABLE_PINCODE_DOCUPLOAD_SELFREPAIR("CREATE_SERVICE_SERVICEABLE_PINCODE_DOCUPLOAD_SELFREPAIR"),
    CUSTOMER_NOT_AVAILABLE_RA_STAGE("CUSTOMER_NOT_AVAILABLE_RA_STAGE", "NON-SELFREPAIR"),
    CUSTOMER_NOT_AVAILABLE("CUSTOMER_NOT_AVAILABLE", "NON-SELFREPAIR"),
    SPARE_PART_NOT_AVAILABLE("SPARE_PART_NOT_AVAILABLE", "NON-SELFREPAIR"),
    SPARE_PART_AVAILABLE("SPARE_PART_AVAILABLE", "NON-SELFREPAIR"),
    IC_APPROVAL_WAITING("IC_APPROVAL_WAITING", "NON-SELFREPAIR"),
    IC_DECISION_BER_APPROVED("IC_DECISION_BER_APPROVED", "NON-SELFREPAIR"),
    IC_DECISION_APPROVED_SELF_REPAIR("IC_DECISION_APPROVED_SELF_REPAIR", "SELFREPAIR"),
    INVOICE_VERIFICATION_SUCCESS("INVOICE_VERIFICATION_SUCCESS", "NON-SELFREPAIR"),
    CANNOT_PERFORM_SERVICE_FOR_SOME_REASON_RA_STAGE("CANNOT_PERFORM_SERVICE_FOR_SOME_REASON_RA_STAGE", "NON-SELFREPAIR"),
    HA_AD_CUSTOMER_PAYMENT("HA_AD_CUSTOMER_PAYMENT", "BOTH"),
    HA_AD_CUSTOMER_PAYMENT_PENDING("HA_AD_CUSTOMER_PAYMENT_PENDING", "BOTH"),
    HA_BD_ACCIDENTAL_DAMAGE("HA_BD_ACCIDENTAL_DAMAGE", "NON-SELFREPAIR"),
    COMPLETE_CLAIM_SETTLEMENT("COMPLETE_CLAIM_SETTLEMENT", "BOTH"),
    DEFAULT("DEFAULT", "BOTH"),
    INSPECTION_SR_RESCHEDULE("INSPECTION_SR_RESCHEDULE", "NON-SELFREPAIR"),
    CANNOT_PERFORM_SERVICE_FOR_SOME_REASON("CANNOT_PERFORM_SERVICE_FOR_SOME_REASON", "NON-SELFREPAIR"),
    REPAIR_SUCCESSFUL("REPAIR_SUCCESSFUL", "NON-SELFREPAIR"),
    TRANSPORTATION_REQUIRED("TRANSPORTATION_REQUIRED", "NON-SELFREPAIR"),
    ESTIMATED_INVOICE_UPLOAD("ESTIMATED_INVOICE_UPLOAD", "SELFREPAIR"),
    IC_DECISION_REJECTED_SELF_REPAIR("IC_DECISION_REJECTED_SELF_REPAIR", "SELFREPAIR"),
    INSPECTION_FAILED("INSPECTION_FAILED", "NON-SELFREPAIR"),
    APPLIANCE_PICKED_FOR_BER("APPLIANCE_PICKED_FOR_BER", "NON-SELFREPAIR"),
    APPLIANCE_PICKED_FOR_REFUND("APPLIANCE_PICKED_FOR_REFUND", "NON-SELFREPAIR"),
    REPAIR_ASSESSMENT_COMPLETED("REPAIR_ASSESSMENT_COMPLETED", "NON-SELFREPAIR"),
    HA_CLAIMS_CLOSE_SERVICE_REQUEST("HA_CLAIMS_CLOSE_SERVICE_REQUEST", "BOTH"),
    DEDUCTIBLE_PAYMENT_DONE("DEDUCTIBLE_PAYMENT_DONE", "NON-SELFREPAIR"),
    CUSTOMER_RESCHEDULE_VISIT_POST_DEDUCTIBLE_PAYMENT("CUSTOMER_RESCHEDULE_VISIT_POST_DEDUCTIBLE_PAYMENT", "NON-SELFREPAIR"),
    SERVICE_REQUEST_UPDATE("SERVICE_REQUEST_UPDATE"),
    UPDATE_STAGE_COMPLETE("UPDATE_STAGE_COMPLETE"),
    UPDATE_STAGE_INCOMPLETE("UPDATE_STAGE_INCOMPLETE"),
    VERIFICATION_UNSUCCESSFUL("VERIFICATION_UNSUCCESSFUL", "BOTH"),
    VERIFICATION_SUCCESSFUL("VERIFICATION_SUCCESSFUL", "BOTH");

    private final String requestEventCode;
    private final String eventApplicability;

    private ServiceRequestEventCode(String requestEventCode) {
        this(requestEventCode, null);
    }

    private ServiceRequestEventCode(String requestEventCode, String eventApplicability) {
        this.requestEventCode = requestEventCode;
        this.eventApplicability = eventApplicability;
    }

    public String getServiceRequestEvent() {
        return this.requestEventCode;
    }

    public String getEventApplicability() {
        return eventApplicability;
    }

    public static ServiceRequestEventCode getServiceRequestEvent(String requestEventCode) {
        for (ServiceRequestEventCode enumEvent : ServiceRequestEventCode.values()) {
            if (enumEvent.getServiceRequestEvent().equals(requestEventCode)) {
                return enumEvent;
            }
        }
        return null;
    }
}
