alter session set current_schema=oneassist;
------------------------------------------------------------------
--Inserting a Dummy Pincode
------------------------------------------------------------------

Insert into OA_PINCODE_MST (PIN_CODE,CITY_CODE,CREATED_BY,CREATED_DATE,STATUS,MODIFIED_BY,MODIFIED_DATE) values (999999,'NDLC','OASYSADMIN',to_timestamp('20-DEC-17 05.41.08.000000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'A',null,null);


------------------------------------------------------------------
--Script to Create Partner,Partner BU and Service Center User
------------------------------------------------------------------

Insert into OA_PARTNER_MST (PARTNER_CODE,PARTNER_TYPE,PARTNER_NAME,CITY,CORPORATE_EMAIL_ID,CORPORATE_LL_NO,CORPORATE_MOBILE_NO,CORPORATE_FAX_NO,PARTNER_STATUS,CONTACT_PERSON_NAME,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,ALT_CORPORATE_EMAILID,COMPANY_CODE,COMPANY_NAME,SRC_CHANNEL_CODE,LINE1,LINE2,LANDMARK,STATE,PINCODE,INDUSTRY,BUSINESS_PARTNER_TYPE) values (287,'1','PRODTEST','NDLC','prodtestsc@mailinator.com',1111111111,1111111111,null,'A',null,'tbhbs',to_date('20-DEC-17','DD-MON-RR'),'979649',to_timestamp('20-DEC-17 01.42.09.661000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,null,'SERVICE_CENTER',null,null,'park','DL','999999','SERVICE CENTER','SERVICE_CENTER');

Insert into OA_PARTNER_BU_MST (PARTNER_BU_CODE,PARTNER_CODE,BU_CODE,BU_NAME,CORPORATE_EMAILID,CORPORATE_ALT_EMAILID,CORPORATE_LL_NO,CORPORATE_MOBILE_NO,CORPORATE_FAX_NO,STATUS,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,LINE1,LINE2,LANDMARK,STATE,CITY,PINCODE,INDUSTRY,BUSINESS_UNIT_TYPE,GST_ADDRESS) values (4600,287,null,'PRODTESTSC','prodserviceusertest@mailinator.com',null,null,4444444444,null,'A','1121583',to_timestamp('20-DEC-17 01.53.27.065000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'979649',to_timestamp('20-DEC-17 01.52.49.576000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,null,'DL','DL','999999',null,'SERVICE_CENTER','Customer''s Address');

Insert into OA_PARTNER_USR_DTL (PARTNER_USERID,PARTNER_CODE,USER_FIRSTNAME,USER_MIDDLENAME,USER_LASTNAME,USER_EMAILID,LL_NO,MOBILE_NO,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,BU_CODE,PASSKEY,PROFILE_IMAGE_STORAGE_REF_ID,MOBILE_NO1,EXPERIENCE) values (3282274,287,'prodserviceuser',null,'test','prodserviceusertest@mailinator.com',null,4444444444,null,null,'admin',to_timestamp('20-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'tbhbs',to_timestamp('20-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'A',4600,'wopdxcksU8dug5nxB1pZWRAgTPr0jjuEhdR03%2B8krf4wSywoGgZAsKSit1xbC1a3',null,null,null);

Insert into OA_USER_LOGIN_INFO (USER_ID,USER_TYPE,LAST_LOGIN_DATE,LAST_LOGIN_IP,CURRENT_LOGIN_IP,CURRENT_LOGIN_DATE,PREVIOUS_PASS,SECRET_QTN_CODE,SECRET_QTN_ANS,USER_LOGIN_ID,USER_PASS,WRONG_PASS_COUNT,FORGOTPASS_LASTDATE,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,USER_PASS_LOCK,PASSWORD_EXPIRE,PASS_EXPIRY,CHANGE_PASS,STATUS,RESET_LINK_EXPIRY,RESET_LINK_STATUS,WRONG_SECRET_COUNT,DOCUSAFE_LOCK,INITIATING_SYS) values (3282274,'WebBusinessPartner',null,null,null,null,null,null,null,'prodserviceusertest@mailinator.com','SKzrGoLPHhopFewEEDaec8+tM/E=',0,null,null,null,'admin',to_timestamp('20-DEC-17 01.52.49.596000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0,to_date('19-APR-18','DD-MON-RR'),null,'Y','A',to_date('04-JAN-18','DD-MON-RR'),1,null,null,2);

Insert into OA_ROLE_USR_DTL (ROLE_ID,OPS_USR_ID,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (1056,3282274,null,null,'admin',to_timestamp('20-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null);


------------------------------
--Script to Create Technician
------------------------------

Insert into OA_PARTNER_USR_DTL (PARTNER_USERID,PARTNER_CODE,USER_FIRSTNAME,USER_MIDDLENAME,USER_LASTNAME,USER_EMAILID,LL_NO,MOBILE_NO,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,STATUS,BU_CODE,PASSKEY,PROFILE_IMAGE_STORAGE_REF_ID,MOBILE_NO1,EXPERIENCE) values (3282275,287,'prodtechnician',null,'test','prodtechicianuser@mailinator.com',null,5555555555,null,null,'Admin',to_timestamp('20-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,'A',4600,'txEm5JW8224TrTZ0XByO%2BhalmAIf1srqQDmFhOCUtBdei3lW%2FVkp5g%3D%3D',null,null,5);

Insert into OA_USER_LOGIN_INFO (USER_ID,USER_TYPE,LAST_LOGIN_DATE,LAST_LOGIN_IP,CURRENT_LOGIN_IP,CURRENT_LOGIN_DATE,PREVIOUS_PASS,SECRET_QTN_CODE,SECRET_QTN_ANS,USER_LOGIN_ID,USER_PASS,WRONG_PASS_COUNT,FORGOTPASS_LASTDATE,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,USER_PASS_LOCK,PASSWORD_EXPIRE,PASS_EXPIRY,CHANGE_PASS,STATUS,RESET_LINK_EXPIRY,RESET_LINK_STATUS,WRONG_SECRET_COUNT,DOCUSAFE_LOCK,INITIATING_SYS) values (3282275,'WebBusinessPartner',null,null,null,null,null,null,null,'prodtechicianuser@mailinator.com','SKzrGoLPHhopFewEEDaec8+tM/E=',0,null,null,null,'Admin',to_timestamp('20-DEC-17 01.59.38.608000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0,to_date('19-APR-18','DD-MON-RR'),null,'Y','A',to_date('04-JAN-18','DD-MON-RR'),1,null,null,2860854);

Insert into OA_ROLE_USR_DTL (ROLE_ID,OPS_USR_ID,AUTH_BY,AUTH_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (1057,3282275,null,null,'Admin',to_timestamp('20-DEC-17 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null);

commit;