ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

ALTER TABLE OA_SERV_REQ_STAGE_MST ADD STAGE_OBJECT_NAME  VARCHAR2(100);
ALTER TABLE OA_SERVICE_REQUEST_DTL ADD REMARK  VARCHAR2(255);
ALTER TABLE OA_SERVICE_REQUEST_DTL ADD EXTERNAL_SR_REFERENCE_ID VARCHAR2(100);
ALTER TABLE OA_SERVICE_REQUEST_DTL ADD INSURANCE_PARTNER_CODE NUMBER(10);

alter table OA_SERVICE_REQUEST_ASSETS_DTL add ASSET_REFERENCE_NO varchar2(10);

alter table OA_SERVICE_REQUEST_ASSETS_DTL modify (PRODUCT_CODE varchar2(10) NULL);

BEGIN
 FOR service_requests IN (
  select * from OA_SERVICE_REQUEST_DTL osrd join OA_SERVICE_REQUEST_TYPE_MST osrtm on osrd.SERVICE_REQUEST_TYPE_ID=osrtm.SERVICE_REQUEST_TYPE_ID where osrtm.SERVICE_REQUEST_TYPE in ('HA_EW','HA_BD') 
 )
 LOOP
   Insert into OA_SERVICE_REQUEST_ASSETS_DTL (ASSET_ID,SERVICE_REQUEST_ID,ASSET_REFERENCE_NO) values (sys_guid(), service_requests.SERVICE_REQUEST_ID,service_requests.REF_SECONDARY_TRACKING_NO);
   END LOOP;
END;
/


ALTER TABLE OA_SERVICE_REQUEST_DTL ADD ADVICE_ID  NUMBER(12);
COMMENT ON column OA_SERVICE_REQUEST_DTL.ADVICE_ID  IS 'Advice Id for payment.';

ALTER TABLE OA_SERVICE_REQUEST_DTL MODIFY REQUEST_DESCRIPTION VARCHAR(1000) ;

commit;