ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Front touch screen','ISSUE','LAP','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Back screen','ISSUE','LAP','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Camera','ISSUE','LAP','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Button','ISSUE','LAP','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Others','ISSUE','LAP','A','oneassist',sysdate);

insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Front touch screen','ISSUE','WR','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Back screen','ISSUE','WR','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Camera','ISSUE','WR','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Button','ISSUE','WR','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Others','ISSUE','WR','A','oneassist',sysdate);

insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Front touch screen','ISSUE','MP01','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Back screen','ISSUE','MP01','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Camera','ISSUE','MP01','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Button','ISSUE','MP01','A','oneassist',sysdate);
insert into OA_SERVICE_TASK_MST( SERVICE_TASK_ID, TASK_NAME,TASK_TYPE,REFERENCE_CODE,STATUS,CREATED_BY,CREATED_ON)values(SEQ_OA_SERVICE_TASK_MST.nextval,'Others','ISSUE','MP01','A','oneassist',sysdate);
commit;

