ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

ALTER TABLE "OA_SERVICE_REQUEST_HST"  ADD "CUSTOMER_ID" NUMBER(10,0);
ALTER TABLE "OA_SERVICE_REQUEST_HST" ADD "REMARK" VARCHAR2(255 BYTE);
ALTER TABLE "OA_SERVICE_REQUEST_HST" ADD "EXTERNAL_SR_REFERENCE_ID" VARCHAR2(100 BYTE);
ALTER TABLE "OA_SERVICE_REQUEST_HST" ADD "PENDENCY" CLOB;
ALTER TABLE "OA_SERVICE_REQUEST_HST" ADD "ADVICE_ID" NUMBER(12,0);