ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;
Insert into oa_doc_type_mst (DOC_TYPE_ID,DOC_NAME,IS_MANDATORY,DESCRIPTION,STATUS) values (SEQ_OA_DOC_TYPE_MST.nextval,'FIR_COPY','N','FIR Copy','A');

Insert into oa_doc_type_mst (DOC_TYPE_ID,DOC_NAME,IS_MANDATORY,DESCRIPTION,STATUS) values (SEQ_OA_DOC_TYPE_MST.nextval,'DAMAGED_APPLIANCE_IMAGE_1','N','Damaged appliance image 1','A');

Insert into oa_doc_type_mst (DOC_TYPE_ID,DOC_NAME,IS_MANDATORY,DESCRIPTION,STATUS) values (SEQ_OA_DOC_TYPE_MST.nextval,'DAMAGED_APPLIANCE_IMAGE_2','N','Damaged appliance image 2','A');

INSERT INTO OA_SERVICE_REQUEST_TYPE_MST(SERVICE_REQUEST_TYPE_ID,SERVICE_REQUEST_TYPE,STATUS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY)
VALUES (SEQ_OA_SERVICE_REQST_TYPE_MST.nextval,'PE_ADLD','A',sysdate,'ADMIN',sysdate,'ADMIN');

INSERT INTO OA_SERVICE_REQUEST_TYPE_MST(SERVICE_REQUEST_TYPE_ID,SERVICE_REQUEST_TYPE,STATUS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY)
VALUES (SEQ_OA_SERVICE_REQST_TYPE_MST.nextval,'PE_EW','A',sysdate,'ADMIN',sysdate,'ADMIN');

INSERT INTO OA_SERVICE_REQUEST_TYPE_MST(SERVICE_REQUEST_TYPE_ID,SERVICE_REQUEST_TYPE,STATUS,CREATED_ON,CREATED_BY,MODIFIED_ON,MODIFIED_BY)
VALUES (SEQ_OA_SERVICE_REQST_TYPE_MST.nextval,'PE_THEFT','A',sysdate,'ADMIN',sysdate,'ADMIN');
COMMIT;