ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;

UPDATE OA_SERV_REQ_TRANSITION_CONFIG SET TRANSITION_TO_STAGE_STATUS = 'AA1' WHERE EVENT_NAME 
IN ('DOC_SENT_TO_IC_COMPLETED',
'ESTIMATED_INVOICE_VERIFICATION_SUCCESS'); 

update OA_SERV_REQ_TRANSITION_CONFIG set TRANSITION_TO_STAGE_STATUS='AA' where 
TRANSITION_TO_STAGE = 'ID' and TRANSITION_TO_STAGE_STATUS is null;

UPDATE OA_SERV_REQ_STAGE_STATUS_MST SET STAGE_STATUS_CODE = 'AA1'
WHERE STAGE_CODE = 'ID' AND STAGE_STATUS_CODE = 'AA' AND SERVICE_REQUEST_TYPE IN ('HA_EW',
'HA_BD',
'HA_AD');

UPDATE OA_SERV_REQ_STAGE_STATUS_MST SET STAGE_STATUS_CODE = 'AA'
WHERE STAGE_CODE = 'ID' AND STAGE_STATUS_CODE IS NULL;



update OA_SERV_REQ_TRANSITION_CONFIG set TRANSITION_TO_STAGE_STATUS = 'SA' where 
EVENT_NAME='TECHNICIAN_AT_LOCATION_AND_BEGINS_SERVICE';

UPDATE OA_SERV_REQ_STAGE_STATUS_MST SET STAGE_STATUS_CODE='SA' WHERE STAGE_CODE = 'RA' AND STAGE_STATUS_CODE IS NULL;

update OA_SERV_REQ_TRANSITION_CONFIG set TRANSITION_TO_STAGE_STATUS = 'VS' where 
EVENT_NAME='REPAIR_SERVICE_RESCHEDULED_IC_APPROVED';

INSERT INTO OA_GENERIC_KEYSET_VALUE_DTL (VALUE_ID, KEYSET_ID, KEY, VALUE, CREATED_BY)
VALUES (SEQ_OA_GENERIC_KEYSET_VALUE.nextval, (select KEYSET_ID FROM OA_GENERIC_KEYSET_MST WHERE OA_GENERIC_KEYSET_MST.KEYSET_NAME = 'WORKFLOW_STAGE_STATUS'), 'AA1', 'Awaiting Approval', 'admin');

UPDATE OA_SERVICE_REQUEST_DTL SET WORKFLOW_STAGE_STATUS = 'SA' WHERE WORKFLOW_STAGE_STATUS IS NULL
AND WORKFLOW_STAGE = 'RA';

UPDATE OA_SERVICE_REQUEST_DTL SET WORKFLOW_STAGE_STATUS = 'AA' WHERE WORKFLOW_STAGE_STATUS IS NULL
AND WORKFLOW_STAGE = 'ID';

COMMIT;