ALTER SESSION SET CURRENT_SCHEMA=ONEASSIST_SP;
  CREATE TABLE "OA_DOC_TYPE_CONFIG_DTL" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DOC_TYPE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SERVICE_REQUEST_TYPE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IS_MANDATORY" VARCHAR2(10 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"REF_CODE" NUMBER(10,0), 
	"INSURANCE_PARTNER_CODE" NUMBER(10,0), 
	"STATUS" VARCHAR2(1 BYTE), 
	"CREATED_ON" TIMESTAMP (6) DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"MODIFIED_ON" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(50 BYTE), 
	 CONSTRAINT "OA_DOC_TYPE_CONFIG_DTL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ONEASSIST"  ENABLE, 
	 CONSTRAINT "OA_DOC_TYPE_CONFIG_DTL_FK1" FOREIGN KEY ("DOC_TYPE_ID")
	  REFERENCES "OA_DOC_TYPE_MST" ("DOC_TYPE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ONEASSIST" ;

   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."ID" IS 'PRIMARY KEY';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."DOC_TYPE_ID" IS 'Document Type ID which is foreign key from OA_DOC_TYPE_MST table';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."SERVICE_REQUEST_TYPE_ID" IS 'Service Request Type ID';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."IS_MANDATORY" IS 'Possiblevalue- Y/N, Default-N';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."REF_CODE" IS 'Reference code';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."INSURANCE_PARTNER_CODE" IS 'Reference partner code';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."STATUS" IS 'Status is Active (A)/Inactive(X)';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."CREATED_ON" IS 'Created On';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."CREATED_BY" IS 'Created By';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."MODIFIED_ON" IS 'Modified on';
   COMMENT ON COLUMN "OA_DOC_TYPE_CONFIG_DTL"."MODIFIED_BY" IS 'Modified By';

  CREATE INDEX "OA_DOC_TYPE_CONFIG_DTL_INDEX1" ON "OA_DOC_TYPE_CONFIG_DTL" ("DOC_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ONEASSIST" ;

  CREATE INDEX "OA_DOC_TYPE_CONFIG_DTL_INDEX2" ON "OA_DOC_TYPE_CONFIG_DTL" ("SERVICE_REQUEST_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ONEASSIST" ;


CREATE SEQUENCE  "SEQ_OA_DOC_TYPE_CONFIG_DTL"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
commit;