Insert into ONEASSIST.OA_CLAIM_HUB_MST (HUB_ID_PK,HUB_NAME,HUB_ADDRESS,HUB_CITY,HUB_STATE,HUB_REGION,HUB_EMAIL,HUB_MOBILE,HUB_CREATED_DATE,HUB_CREATED_BY,HUB_MODIFIED_DATE,HUB_MODIFIED_BY,HUB_PINCODE) values (27,'SAMSUNG NORTH','38,Nishant Kunj,Kohat Enclave,Near Kohat Metro Station,Pritampura','DL','DL','CENTRAL','rameshwartrader.hhp@gmail.com',8700188177,SYSDATE,'SCRIPT',SYSDATE,null,'110034');

INSERT INTO ONEASSIST.OA_PARTNER_BU_HUB_RLN VALUES(4388,27,'SAMSUNG');

COMMIT;